#
# gen_loader_blob.ps1
# -------------------
# Reads a raw binary file (loader_func.bin) and emits a C header that
# declares the bytes as a static const unsigned char array.
#
# Usage (called by the Makefile):
#   powershell -NoProfile -ExecutionPolicy Bypass -File gen_loader_blob.ps1 `
#              -BinPath client/loader_func.bin -OutPath client/loader_blob.h
#

param(
    [Parameter(Mandatory=$true)]  [string] $BinPath,
    [Parameter(Mandatory=$true)]  [string] $OutPath
)

$bytes = [System.IO.File]::ReadAllBytes($BinPath)
$count = $bytes.Length

$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine("/*")
[void]$sb.AppendLine(" * client/loader_blob.h  --  AUTO-GENERATED by gen_loader_blob.ps1")
[void]$sb.AppendLine(" * Do not edit by hand.  Regenerate by running: make $(Split-Path $OutPath -Leaf)")
[void]$sb.AppendLine(" */")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#ifndef CLIENT_LOADER_BLOB_H")
[void]$sb.AppendLine("#define CLIENT_LOADER_BLOB_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("/* Raw position-independent rfl_loader() machine code */")
[void]$sb.AppendLine("static const unsigned char s_rfl_loader[] = {")

$cols = 16
for ($i = 0; $i -lt $count; $i += $cols) {
    $chunk = $bytes[$i .. [Math]::Min($i + $cols - 1, $count - 1)]
    $hex   = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
    if ($i + $cols -lt $count) { $hex += "," }
    [void]$sb.AppendLine("    $hex")
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define S_RFL_LOADER_SIZE  ((DWORD)sizeof(s_rfl_loader))")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif /* CLIENT_LOADER_BLOB_H */")

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
Write-Host "[+] Wrote $count bytes to $OutPath"
